package kr.co.kpcard.backoffice.repository.account.mapper;

import java.util.List;

import kr.co.kpcard.backoffice.component.account.AccountParam;
import kr.co.kpcard.backoffice.component.account.AccountSalementParam;
import kr.co.kpcard.backoffice.repository.account.model.AccountApprovalSumm;
import kr.co.kpcard.backoffice.repository.account.model.AccountChargement;
import kr.co.kpcard.backoffice.repository.account.model.AccountPayment;
import kr.co.kpcard.backoffice.repository.account.model.AccountSalement;
import kr.co.kpcard.backoffice.repository.account.model.AccountSalementSumm;
import kr.co.kpcard.backoffice.repository.account.model.AccountSummaryModel;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface AccountMapper {
	public static final String GET_PAYMENTS_BY_COUNT = "<script> "
			+"SELECT count(1)                                                         AS count                "//-- 총 조회 건수              "
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , 1 , 0))       , 0) AS amountCount       "// -- 총 결제 건수              "
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , 1 , 0))       , 0) AS cancelCount        "//-- 총 취소 건수               "
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , 1 , 0))       , 0) AS refundCount       "// -- 총 환불 건수              "
			+"       , NVL(SUM(CASE WHEN A.approval_status  = 'PAYT-0002'                                        "
			+"                      THEN A.amount * -1                                                           "
			+"                      ELSE A.amount                                                                "
			+"                   END ), 0)                                                 AS totalSum          "// -- 총 금액                   "       
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.amount , 0)), 0) AS amountSum         "// -- 총 거래 금액              "
			+"		 , NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , NVL(A.ORIG_AMOUNT, A.amount), 0)), 0) AS origAmountSum         "//-- 총 결제 금액 "
			+"	 	 , NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.DC_AMOUNT , 0)), 0) AS dcAmountSum         "//-- 총 결제 금액 "
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , A.amount , 0)), 0) AS cancelSum          "//-- 총 거래취소 금액              "
			+"		 , NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , NVL(A.ORIG_AMOUNT, A.amount), 0)), 0) AS origCancelSum         "//-- 총 결제 취소금액 "
			+"       , NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , A.amount , 0)), 0) AS refundSum          "//-- 총 환불 금액              "
			+"       , NVL(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status  = 'PAYT-0001'  "//-- 비율정산                  "
			+"                      THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0)                                                     "
			+"                      WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status &lt;&gt; 'PAYT-0001'                              "
			+"                      THEN ROUND(((A.amount* -1) * A.MERCHANT_COMMISION) /100,0)                                               "
			+"                      WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status  = 'PAYT-0001'  "//-- 건당                      "
			+"                      THEN A.MERCHANT_COMMISION                                                                                "
			+"                      WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status &lt;&gt; 'PAYT-0001'  "//-- 건당                      "
			+"                      THEN A.MERCHANT_COMMISION * -1                                                                           "
			+"                      ELSE 0                                                                                                   "
			+"                   END ), 0) AS billingSum        "
			+"		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0003',  (NVL(A.ORIG_AMOUNT, A.amount) -  (CASE"
			+"																								WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' AND A.approval_status     = 'PAYT-0001'"
            +"							                                                                    THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0)"
            +"   						                                                                    WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' AND A.approval_status    &lt;&gt; 'PAYT-0001'"
            +"							                                                                    THEN ROUND(((A.amount* -1) * A.MERCHANT_COMMISION) /100,0)"
            +"						                                                                        WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' AND A.approval_status     = 'PAYT-0001'"
            +"																								THEN A.MERCHANT_COMMISION"
            +"						                                                                        WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' AND A.approval_status    &lt;&gt; 'PAYT-0001'"
            +"							                                                                    THEN A.MERCHANT_COMMISION * -1"
            +"							                                                                    ELSE 0 END)"
            +"															), 0"
            +"  					)"
    		+"				)"
			+"		, 0) provideAmountSum "																				//-- 총 정산 금액"
			+"    FROM PAY_APPROVAL A                                                                                                        "
			+"       , SUBMERCHANT  B                                                                                                       "
			+"       , SUBMERCHANT_SERVICE C                                                                                                 "      
			+"    WHERE 1 = 1 "
			+" 			<if test='excelAllFlag != \"\" '> AND 1 = 2 </if> "  
			+"				AND B.del_flag = 'N' "
			+ "				AND A.submerchant_id = B.submerchant_id "
			+ "				AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "				AND A.submerchant_id = C.submerchant_id(+) "
			+ "				AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " <if test='merchantId != \"\" '> "
	        + "		AND A.submerchant_id = #{merchantId} "
	        + " </if> "
	        + " <if test='serviceNm != \"\" and serviceNm != null'> "
	        + " 	AND A.service_nm LIKE '%' || #{serviceNm} || '%' "
	        + " </if> "  
	        + " <if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "		AND A.approval_status IN "
	        + " 	<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   #{item} "
    		+ "		</foreach>"
	        + " </if> " 
	        + " <if test='serviceId != \"\" '> "
	        + "		AND A.service_id = #{serviceId} "
	        + " </if> "
	        + " <if test='approvalNo != \"\" '> "
	        + "		AND A.approval_no = #{approvalNo} "
	        + " </if> "
	        + " <if test='orderNo != \"\" '> "
	        + "		AND A.order_no = #{orderNo} "
	        + " </if> "
	        + " <if test='svcConnId != \"\" '> "
	        + "		AND A.svc_conn_id = #{svcConnId} "
	        + " </if> "
	        + " <if test='payMethod != \"\" '> "
	        + "		AND A.pay_method = #{payMethod} "
	        + " </if> "
	        + " <if test='saleDivider != \"\" '> "
	        + "		AND C.sale_divider = #{saleDivider} "
	        + " </if> "
	        + " <if test='cardType != \"\" and cardType != \"all\" '> "
	        + "		AND A.card_cd IN "
	        + " 	<foreach collection='cardTypeList' item='item' separator=',' open='(' close=')' >"
    		+ "		   #{item} "
    		+ "		</foreach>"
	        + " </if> "
			+ " </script>";
	@Select(GET_PAYMENTS_BY_COUNT)
	public AccountSummaryModel getPaymentsByCount(AccountParam param);
	
	public static final String GET_PAYMENTS = "<script> "
			+ "	SELECT Z.* "
			+ "		FROM ( "
			+ "			SELECT ROWNUM AS RNUM, X.* "
			+ "			FROM ( "
			+ "				SELECT A.seq                            "// -- 결제승인 시퀀스 "
			+ "					, A.summ_seq                        "//-- 결제승인 요약 시퀀스 "
			+ "					, A.submerchant_id                  "//-- 거래처 아이디 "
			+ "					, A.submerchant_nm                  "//-- 거래처명 "
			+ "					, A.service_id                      "//-- 서비스 시퀀스 "
			+ "					, C.name service_nm                 "//-- 서비스명 "
			+ "					, A.service_type                    "//-- 서비스타입 "
			+ "					, A.service_category                "//-- 서비스 카테고리 "
			+ "					, A.svc_conn_id                     "//-- 서비스연동아이디 "
			+ "					, A.deal_divider                    "//-- 거래 구분(거래일/영업일) "
			+ "					, A.deal_dt                         "//-- 거래 구분 일(거래일/영업일) "
			+ "					, A.approval_dt "
			+ "					, FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ "					, A.approval_status                 "//-- 승인상태(결제/취소) "
			+ "					, A.approval_no                     "//-- 승인번호 "
			+ "					, A.order_no                        "//-- 주문번호 "
			+ "					, FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName "
			+ "					, A.card_cd                         "//-- 카드코드 "
			+ "					, A.card_nm                         "//-- 카드명 "
			+ "					, A.card_no                         "//-- 카드번호 "
			+ "					, A.card_enc_no                     "//-- 암호화 카드번호 "
			+ "					, A.card_mng_no                     "//-- 카드관리번호 "
			+ "					, A.amount                          "//-- 할인 금액을 제외한 결제금액 "
			+ "					, NVL(A.ORIG_AMOUNT, AMOUNT) origAmount"//-- 총 결제 금액 "
			+ "					, NVL(A.DC_AMOUNT, 0) dcAmount		"	//-- 할인 금액"
			+ "					, A.balance                         "//-- 잔액 "
			+ "					, FNC_ADMIN_CODE_TO_NAME(A.pay_type) payTypeName "//-- 지불 수단 "
			+ "					, A.pay_type                        "//-- 지불 수단 "
			+ "					, A.pay_method                      "//-- 결제 수단 "
			+ "					, FNC_ADMIN_CODE_TO_NAME(A.pay_method) payMethodName "
			+ "					, C.sale_divider                      "//-- 지불 형태 "
			+ "					, FNC_ADMIN_CODE_TO_NAME(C.sale_divider) saleDividerName "
			+ "					, A.store_cd                        "//-- 매장(점포) 코드 "
			+ "					, A.store_nm                        "//-- 매장(점포) 이름 "
			+ "					, A.pos_no                          "//-- 매장(점포) POS No "
			+ "					, A.cp_id                           "//-- CP ID "     
			+ " 				, A.cp_user_id                      "//-- CP User ID "
			+ "					, A.cp_user_ip                      "//-- CP User IP "
			+ "					, B.agent_id                        "//-- AGENT_ID  "
			+ "					, RTRIM(TO_CHAR(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 " 
			+ " 									THEN ROUND((NVL(A.ORIG_AMOUNT, AMOUNT) * A.MERCHANT_COMMISION) /100,0) " 
			+ " 									WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ " 									THEN A.MERCHANT_COMMISION "
			+ " 									ELSE 0 "
			+ " 									END ,'FM9999999999990.99'),'.') commision  "//-- 충전/결제 건만 합산 "
			+ " 				, RTRIM(TO_CHAR(A.merchant_commision,'FM9999999999990.99'),'.') merchant_commision "
			+ "					, A.merchant_tax_type               "//-- 거래처부가세타입 "
			+ " 				, A.merchant_tax                    "//-- 거래처 부가세 "
			+ " 				, A.kpc_comm_type                   "//-- KPC수수료타입 "
			+ " 				, A.kpc_commision                   "//-- KPC 수수료 "
			+ " 				, A.kpc_tax_type                    "//-- KPC부가세타입 "
			+ " 				, A.kpc_tax                         "//-- KPC 부가세 "
			+ " 				, A.add_comm_type01                 "//-- 추가 수수료타입01 "
			+ " 				, A.add_commision01                 "//-- 부가 수수료 01 "
			+ " 				, A.add_tax_type01                  "//-- 추가 부가세타입01 "
			+ " 				, A.add_tax01                       "//-- 부가 부가세 01 "
			+ " 				, A.add_comm_type02                 "//-- 추가 수수료타입02 "
			+ "					, A.add_commision02                 "//-- 부가 수수료 02 "
			+ " 				, A.add_tax_type02                  "//-- 추가 부가세타입02 "
			+ " 				, A.add_tax02                       "//-- 부가 부가세 02 "
			+ " 				, A.billing_sum                     "//-- 정산 금액 "
			+ " 				, A.desc01                          "//-- 승인 상세01 "
			+ " 				, A.desc02                          "//-- 승인 상세02 "
			+ "				FROM PAY_APPROVAL A "
			+ "					, SUBMERCHANT B "
			+ "					, SUBMERCHANT_SERVICE C "
			+ "				WHERE 1 = 1 "
			+ "					AND B.del_flag = 'N' "
			+ "					AND A.submerchant_id = B.submerchant_id "
			+ "					AND A.submerchant_id = C.submerchant_id(+) "
			+ "					AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "					AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + "				<if test='serviceNm != \"\" and serviceNm!=null'> "
	        + "				 	AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + "				</if> "  
	        + " 			<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "					AND A.approval_status IN "
	        + " 				<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> " 
	        + " 			<if test='serviceId != \"\" '> "
	        + "					AND A.service_id = #{serviceId} "
	        + " 			</if> "
	        + " 			<if test='approvalNo != \"\" '> "
	        + "					AND A.approval_no = #{approvalNo} "
	        + " 			</if> "
	        + " 			<if test='orderNo != \"\" '> "
	        + "					AND A.order_no = #{orderNo} "
	        + " 			</if> "
	        + " 			<if test='svcConnId != \"\" '> "
	        + "					AND A.svc_conn_id = #{svcConnId} "
	        + " 			</if> "
	        + " 			<if test='payMethod != \"\" '> "
	        + "					AND A.pay_method = #{payMethod} "
	        + " 			</if> "
	        + " 			<if test='saleDivider != \"\" '> "
	        + "					AND C.sale_divider = #{saleDivider} "
	        + " 			</if> "
	        + " 			<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "					AND A.card_cd IN "
	        + " 				<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> "
	        + "			) X "
	        + "			WHERE ROWNUM &lt;= #{offset}+#{limit} "
	        + "		) Z "
	        + "	WHERE RNUM &gt; #{offset} "
	        + "	<if test='excelAllFlag == \"\" '> "
	        + " </if> "
			+ " </script> ";
	@Select(GET_PAYMENTS)
	public List<AccountPayment> getPayments(AccountParam param);
	
	public static final String GET_PAYMENT_DAILY_BY_COUNT = "<script> "
			+ "	SELECT count(1) AS count "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , 1 , 0))       , 0) AS amountCount       "//-- 총 결제 금액 "         
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , 1 , 0))       , 0) AS cancelCount       "//-- 총 취소 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , 1 , 0))       , 0) AS refundCount       "//-- 총 환불 건수 "
			+ "		, NVL(SUM(A.amount)                                              , 0) AS totalSum          "//-- 총 승인 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.amount , 0)), 0) AS amountSum         "//-- 총 결제 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.origAmount , 0)), 0) AS origAmountSum         "//-- 총 결제 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.dcAmount , 0)), 0) AS dcAmountSum         "//-- 총 결제 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , A.amount , 0)), 0) AS cancelSum         "//-- 총 취소 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , A.amount , 0)), 0) AS refundSum         "//-- 총 환불 금액 "
			+ "		, NVL(SUM(A.commision ), 0)               AS billingSum        "//-- 총 정산 금액 "
			+ "	FROM ( "
			+ "		SELECT A.approval_status "		
			+ "			,SUM(A.amount) amount "
			+ "			,SUM(A.ORIG_AMOUNT) origAmount "
			+ "			,SUM(A.DC_AMOUNT) dcAmount "
			+ "			,A.merchant_tax_type "
			+ " 		,A.MERCHANT_COMMISION "                      
			+ " 		,SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status  = 'PAYT-0001' "//-- 비율정산 " 
			+ " 				THEN ROUND((NVL(A.ORIG_AMOUNT, AMOUNT) * A.MERCHANT_COMMISION) /100,0) "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status &lt;&gt; 'PAYT-0001' "
			+ " 				THEN ROUND(((NVL(A.ORIG_AMOUNT, AMOUNT)* -1) * A.MERCHANT_COMMISION) /100,0) "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status  = 'PAYT-0001' "//-- 건당 "
			+ " 				THEN A.MERCHANT_COMMISION "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status &lt;&gt; 'PAYT-0001' "//-- 건당 "
			+ " 				THEN A.MERCHANT_COMMISION * -1 " 
			+ "		 		ELSE 0 "
			+ "			END) commision "
			+ "		FROM PAY_APPROVAL A "
			+ "			, SUBMERCHANT B "
			+ "			, SUBMERCHANT_SERVICE C "
			+ "		WHERE 1 = 1 "
			+ " 	<if test='excelAllFlag != \"\" '> "
	        + "			AND 1 = 2 "
	        + " 	</if>"
	        + "			AND B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "					AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + "				<if test='serviceNm != \"\" '> "
	        + "				 	AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + "				</if> "  
	        + " 			<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "					AND A.approval_status IN "
	        + " 				<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> " 
	        + " 			<if test='serviceId != \"\" '> "
	        + "					AND A.service_id = #{serviceId} "
	        + " 			</if> "
	        + " 			<if test='approvalNo != \"\" '> "
	        + "					AND A.approval_no = #{approvalNo} "
	        + " 			</if> "
	        + " 			<if test='orderNo != \"\" '> "
	        + "					AND A.order_no = #{orderNo} "
	        + " 			</if> "
	        + " 			<if test='svcConnId != \"\" '> "
	        + "					AND A.svc_conn_id = #{svcConnId} "
	        + " 			</if> "
	        + " 			<if test='payMethod != \"\" '> "
	        + "					AND A.pay_method = #{payMethod} "
	        + " 			</if> "
	        + " 			<if test='saleDivider != \"\" '> "
	        + "					AND C.sale_divider = #{saleDivider} "
	        + " 			</if> "
	        + " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + " 			<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "					AND A.card_cd IN "
	        + " 				<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach> "
	        + " 			</if> "
	        + " 	GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, A.deal_dt, A.deal_divider, A.pay_type, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION "
	        + "	) A"
			+ " </script> ";
	@Select(GET_PAYMENT_DAILY_BY_COUNT)
	public AccountSummaryModel getPaymentDailyByCount(AccountParam param);
	
	
	public static final String GET_PAYMENT_DAILY = "<script> "
			+ "	SELECT Z.* "
			+ "		FROM ( "
			+ "			SELECT ROWNUM AS RNUM, X.* "
			+ "			FROM ( "
			+ " 			SELECT A.SUBMERCHANT_NM "
			+ " 				,C.name SERVICE_NM "
			+ "					,A.SVC_CONN_ID "
			+ " 				,A.approval_status "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ " 				,A.pay_type "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.pay_type) payTypeName "//-- 지불 수단 "  
			+ " 				,A.card_cd "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName "
			+ " 				,A.deal_dt "
			+ " 				,A.deal_divider "
			+ " 				,count(1) cnt "
			+ " 				,SUM(A.amount) amount "
			+ "					,RTRIM(TO_CHAR(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 " 
			+ "											THEN ROUND((NVL(A.ORIG_AMOUNT, AMOUNT) * A.MERCHANT_COMMISION) /100,0) "
			+ "											WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ "											THEN A.MERCHANT_COMMISION "
			+ "											ELSE 0 "
			+ "										END ),'FM9999999999990.99'),'.') commision "
			+ "				FROM PAY_APPROVAL A "
			+ "					, SUBMERCHANT B "
			+ "					, SUBMERCHANT_SERVICE C "
			+ "				WHERE 1 = 1 "
			+ "					AND B.del_flag = 'N' "
			+ "					AND A.submerchant_id = B.submerchant_id "
			+ "					AND A.submerchant_id = C.submerchant_id(+) "
			+ "					AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "					AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + "				<if test='serviceNm != \"\" '> "
	        + "				 	AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + "				</if> "
	        + " 			<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "					AND A.approval_status IN "
	        + " 				<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> " 
	        + " 			<if test='serviceId != \"\" '> "
	        + "					AND A.service_id = #{serviceId} "
	        + " 			</if> "
	        + " 			<if test='approvalNo != \"\" '> "
	        + "					AND A.approval_no = #{approvalNo} "
	        + " 			</if> "
	        + " 			<if test='orderNo != \"\" '> "
	        + "					AND A.order_no = #{orderNo} "
	        + " 			</if> "
	        + " 			<if test='svcConnId != \"\" '> "
	        + "					AND A.svc_conn_id = #{svcConnId} "
	        + " 			</if> "
	        + " 			<if test='payMethod != \"\" '> "
	        + "					AND A.pay_method = #{payMethod} "
	        + " 			</if> "
	        + " 			<if test='saleDivider != \"\" '> "
	        + "					AND C.sale_divider = #{saleDivider} "
	        + " 			</if> "
	        + " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + " 			<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "					AND A.card_cd IN "
	        + " 				<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach> "
    		+ " 			</if> "
    		+ "				GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, A.deal_dt, A.deal_divider, A.pay_type, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION "
    		+ "			) X "
    		+ "			WHERE ROWNUM &lt;= #{offset} + #{limit}"
    		+ "		) Z "
    		+ "	WHERE RNUM &gt; #{offset} "
    		+ "	<if test='excelAllFlag == \"\" '> "
	        + "	ORDER BY deal_dt DESC "
	        + " </if> "
			+ " </script>";
	@Select(GET_PAYMENT_DAILY)
	public List<AccountApprovalSumm> getPaymentDaily(AccountParam param);
	
	public static final String GET_PAYMENT_MONTH_BY_COUNT = "<script> "
			+ "	SELECT count(1) AS count "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , 1 , 0))       , 0) AS amountCount       "//-- 총 결제 금액 "         
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , 1 , 0))       , 0) AS cancelCount       "//-- 총 취소 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , 1 , 0))       , 0) AS refundCount       "//-- 총 환불 건수 "
			+ "		, NVL(SUM(A.amount)                                              , 0) AS totalSum          "//-- 총 승인 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0001' , A.amount , 0)), 0) AS amountSum         "//-- 총 결제 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0002' , A.amount , 0)), 0) AS cancelSum         "//-- 총 취소 금액 "
			+ "		, NVL(SUM(DECODE(A.approval_status , 'PAYT-0003' , A.amount , 0)), 0) AS refundSum         "//-- 총 환불 금액 "
			+ "		, NVL(SUM(A.commision ), 0)               AS billingSum        "//-- 총 정산 금액 "
			+ "	FROM ( "
			+ "		SELECT A.approval_status "		
			+ "			,SUM(A.amount) amount "
			+ "			,A.merchant_tax_type "
			+ " 		,A.MERCHANT_COMMISION "                      
			+ " 		,SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status  = 'PAYT-0001' "//-- 비율정산 " 
			+ " 				THEN ROUND((NVL(A.ORIG_AMOUNT, AMOUNT)* A.MERCHANT_COMMISION) /100,0) "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status &lt;&gt; 'PAYT-0001' "
			+ " 				THEN ROUND(((NVL(A.ORIG_AMOUNT, AMOUNT)* -1) * A.MERCHANT_COMMISION) /100,0) "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status  = 'PAYT-0001' "//-- 건당 "
			+ " 				THEN A.MERCHANT_COMMISION "
			+ " 				WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status &lt;&gt; 'PAYT-0001' "//-- 건당 "
			+ " 				THEN A.MERCHANT_COMMISION * -1 " 
			+ "		 		ELSE 0 "
			+ "			END) commision "
			+ "		FROM PAY_APPROVAL A "
			+ "			, SUBMERCHANT B "
			+ "			, SUBMERCHANT_SERVICE C "
			+ "		WHERE 1 = 1 "
			+ " 	<if test='excelAllFlag != \"\" '> "
	        + "			AND 1 = 2 "
	        + " 	</if>"
	        + "			AND B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + "				<if test='serviceNm != \"\" '> "
	        + "				 	AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + "				</if> "  
	        + " 			<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "					AND A.approval_status IN "
	        + " 				<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> " 
	        + " 			<if test='serviceId != \"\" '> "
	        + "					AND A.service_id = #{serviceId} "
	        + " 			</if> "
	        + " 			<if test='approvalNo != \"\" '> "
	        + "					AND A.approval_no = #{approvalNo} "
	        + " 			</if> "
	        + " 			<if test='orderNo != \"\" '> "
	        + "					AND A.order_no = #{orderNo} "
	        + " 			</if> "
	        + " 			<if test='svcConnId != \"\" '> "
	        + "					AND A.svc_conn_id = #{svcConnId} "
	        + " 			</if> "
	        + " 			<if test='payMethod != \"\" '> "
	        + "					AND A.pay_method = #{payMethod} "
	        + " 			</if> "
	        + " 			<if test='saleDivider != \"\" '> "
	        + "					AND C.sale_divider = #{saleDivider} "
	        + " 			</if> "
	        + " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + " 			<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "					AND A.card_cd IN "
	        + " 				<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach> "
	        + " 			</if> "
	        + "				GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, SUBSTR(A.deal_dt,1,6), A.deal_divider, A.pay_type, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION"
	        + "	) A"
			+ " </script> ";
	@Select(GET_PAYMENT_MONTH_BY_COUNT)	
	public AccountSummaryModel getPaymentMonthByCount(AccountParam param);
	
	public static final String GET_PAYMENT_MONTH = "<script> "
			+ "	SELECT Z.* "
			+ "		FROM ( "
			+ "			SELECT ROWNUM AS RNUM"
			+ "				, X.* "
			+ "			FROM ( "
			+ " 			SELECT A.SUBMERCHANT_NM "
			+ " 				,C.name SERVICE_NM "
			+ "					,A.SVC_CONN_ID "
			+ " 				,A.approval_status "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ " 				,A.pay_type "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.pay_type) payTypeName "//-- 지불 수단 "  
			+ " 				,A.card_cd "
			+ " 				,FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName "
			+ " 				,SUBSTR(A.deal_dt,1,6) deal_dt"
			+ " 				,A.deal_divider "
			+ " 				,count(1) cnt "
			+ " 				,SUM(A.amount) amount "
			+ "					,RTRIM(TO_CHAR(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 " 
			+ "											THEN ROUND((NVL(A.ORIG_AMOUNT, AMOUNT) * A.MERCHANT_COMMISION) /100,0) "
			+ "											WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ "											THEN A.MERCHANT_COMMISION "
			+ "											ELSE 0 "
			+ "										END ),'FM9999999999990.99'),'.') commision "
			+ "				FROM PAY_APPROVAL A "
			+ "					, SUBMERCHANT B "
			+ "					, SUBMERCHANT_SERVICE C "
			+ "				WHERE 1 = 1 "
			+ "					AND B.del_flag = 'N' "
			+ "					AND A.submerchant_id = B.submerchant_id "
			+ "					AND A.submerchant_id = C.submerchant_id(+) "
			+ "					AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "					AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + "				<if test='serviceNm != \"\" '> "
	        + "				 	AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + "				</if> "
	        + " 			<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "					AND A.approval_status IN "
	        + " 				<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach>"
	        + " 			</if> " 
	        + " 			<if test='serviceId != \"\" '> "
	        + "					AND A.service_id = #{serviceId} "
	        + " 			</if> "
	        + " 			<if test='approvalNo != \"\" '> "
	        + "					AND A.approval_no = #{approvalNo} "
	        + " 			</if> "
	        + " 			<if test='orderNo != \"\" '> "
	        + "					AND A.order_no = #{orderNo} "
	        + " 			</if> "
	        + " 			<if test='svcConnId != \"\" '> "
	        + "					AND A.svc_conn_id = #{svcConnId} "
	        + " 			</if> "
	        + " 			<if test='payMethod != \"\" '> "
	        + "					AND A.pay_method = #{payMethod} "
	        + " 			</if> "
	        + " 			<if test='saleDivider != \"\" '> "
	        + "					AND C.sale_divider = #{saleDivider} "
	        + " 			</if> "
	        + " 			<if test='merchantId != \"\" '> "
	        + "					AND A.submerchant_id = #{merchantId} "
	        + " 			</if> "
	        + " 			<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "					AND A.card_cd IN "
	        + " 				<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   				#{item} "
    		+ "					</foreach> "
    		+ " 			</if> "
    		+ "				GROUP BY A.SUBMERCHANT_NM , C.name , A.SVC_CONN_ID, A.approval_status, SUBSTR(A.deal_dt,1,6), A.deal_divider, A.pay_type, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION"
    		+ "			) X "
    		+ "			WHERE ROWNUM &lt;= (#{offset}+#{limit})"
    		+ "		) Z "
    		+ "	WHERE RNUM &gt; #{offset} "
    		+ "	<if test='excelAllFlag == \"\" '> "
	        + " </if> "
			+ " </script>";
	@Select(GET_PAYMENT_MONTH)
	public List<AccountApprovalSumm> getPaymentMonth(AccountParam param);
	
	
	public static final String GET_CHARGMENTS_BY_COUNT = "<script> "
			+ "	SELECT count(1)                                                         AS count              "//  -- 총 조회 건수  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN 1 END), 0) AS amountCount      "// -- 총 결제 금액  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN 1 END), 0) AS cancelCount      "// -- 총 취소 금액 "
			+ " 	, 0                                                                   AS refundCount      "// -- 총 환불 금액 "
			+ " 	, NVL(SUM(A.amount)                                              , 0) AS totalSum         "// -- 총 승인 금액 "
			+ "		, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN A.AMOUNT END), 0) AS amountSum        "// -- 총 결제 금액 "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN A.AMOUNT END), 0) AS cancelSum        "// -- 총 취소 금액 "
			+ " 	, 0                                                                   AS refundSum        "// -- 총 환불 금액 "
			+ " 	, NVL(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') "//-- 비율정산 "
			+ "						THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') "
			+ "						THEN ROUND(((A.amount* -1) * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') "//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status  IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') "//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION * -1 "
			+ "						ELSE 0 "
			+ "					END ), 0)               AS billingSum        "//-- 총 정산 금액 "
			+ "	FROM CHARGE_APPROVAL A "
			+ "		, SUBMERCHANT B "
			+ "		, SUBMERCHANT_SERVICE C "
			+ "	WHERE 1 = 1 "
			+ " 	<if test='excelAllFlag != \"\" '> "
	        + "			AND 1 = 2 "
	        + " 	</if>"
	        + "			AND B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> " 
			+ "</script>";
	@Select(GET_CHARGMENTS_BY_COUNT)
	public AccountSummaryModel getChargmentsByCount(AccountParam param);
	
	public static final String GET_CHARGMENTS = "<script> "
			+ "SELECT Z.* "       
			+ "FROM ( "       
			+ "		SELECT ROWNUM AS RNUM, X.* "
			+ "		FROM ( "
			+ "			SELECT A.seq                       "//      -- 결제승인 시퀀스 "
			+ "			,A.summ_seq                        "//-- 결제승인 요약 시퀀스 "
			+ "			,A.submerchant_id                  "//-- 거래처 아이디 "
			+ "			,A.submerchant_nm                  "//-- 거래처명 "
			+ "			,A.service_id                      "//-- 서비스 시퀀스 "
			+ "			,C.name service_nm                 "//-- 서비스명 "
			+ "			,A.service_type                    "//-- 서비스타입 "
			+ "			,A.service_category                "//-- 서비스 카테고리 "
			+ "			,A.svc_conn_id                     "//-- 서비스연동아이디 "
			+ "			,A.deal_divider                    "//-- 거래 구분(거래일/영업일) "
			+ "			,A.deal_dt                         "//-- 거래 구분 일(거래일/영업일) "
			+ "			,A.approval_dt                     "//-- 승인일시 "
			+ "			,FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ "			,A.approval_status                 "//-- 승인상태(충전/취소) "
			+ "			,A.approval_no                     "//-- 승인번호 "
			+ "			,A.order_no                        "//-- 주문번호 "
			+ "			,FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName     "//   -- 카드구분 "
			+ "			, C.sale_divider                      "//-- 지불 형태 "
			+ "			, FNC_ADMIN_CODE_TO_NAME(C.sale_divider) saleDividerName "
			+ "			,A.card_cd                         "//-- 카드코드 "
			+ "			,A.card_nm                         "//-- 카드명 "
			+ "			,A.card_no                         "//-- 카드번호 "
			+ "			,A.card_enc_no "
			+ "			,A.card_mng_no                     "//-- 카드관리번호 "
			+ "			,A.amount                          "//-- 결제 금액 "
			+ "			,A.balance                         "//-- 잔액 "
			+ "			,A.charge_type                     "//-- 구분 "
			+ "			,FNC_ADMIN_CODE_TO_NAME(A.charge_type) chargeTypeName "
			+ "			,A.charge_method                  "// -- 지불 수단 "
			+ "			,FNC_ADMIN_CODE_TO_NAME(A.charge_method) chargeMethodName "
			+ "			,FNC_ADMIN_CODE_TO_NAME(A.charge_status) chargeStatusName "
			+ "			,A.store_cd                       "// -- 매장(점포) 코드 "
			+ "			,A.store_nm                       "// -- 매장(점포) 이름 "
			+ "			,A.pos_no                         "// -- 매장(점포) POS No "
			+ "			,A.cp_id                          "// -- CP ID "
			+ "			,A.cp_user_id                     "// -- CP User ID "
			+ "			,A.cp_user_ip                     "// -- CP User IP "
			+ "			,B.agent_id "
			+ "			,A.merchant_comm_type             "// -- 거래처수수료타입 "
			+ "			,RTRIM(TO_CHAR(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 "
			+ "								THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ "								WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ "								THEN A.MERCHANT_COMMISION "
			+ "								ELSE 0 "
			+ "							END ,'FM9999999999990.99'),'.') commision  "//-- 충전/결제 건만 합산 " 
			+ "			,RTRIM(TO_CHAR(A.merchant_commision,'FM9999999999990.99'),'.') merchant_commision "
			+ "			,A.merchant_tax_type              "// -- 거래처부가세타입 "
			+ "			,A.merchant_tax                   "// -- 거래처 부가세 "
			+ "			,A.kpc_comm_type                  "// -- KPC수수료타입 "
			+ "			,A.kpc_commision                  "// -- KPC 수수료 "
			+ "			,A.kpc_tax_type                   "// -- KPC부가세타입 "
			+ "			,A.kpc_tax                        "// -- KPC 부가세 "
			+ "			,A.add_comm_type01                "// -- 추가 수수료타입01 "
			+ "			,A.add_commision01                "// -- 부가 수수료 01 "
			+ "			,A.add_tax_type01                 "// -- 추가 부가세타입01 "
			+ "			,A.add_tax01                      "// -- 부가 부가세 01 "
			+ "			,A.add_comm_type02                "// -- 추가 수수료타입02 "
			+ "			,A.add_commision02                "// -- 부가 수수료 02 "
			+ "			,A.add_tax_type02                 "// -- 추가 부가세타입02 "
			+ "			,A.add_tax02                      "// -- 부가 부가세 02 "
			+ "			,A.billing_sum                    "// -- 정산 금액 "
			+ "			,A.desc01                         "// -- 승인 상세01 "
			+ "			,A.desc02                         "// -- 승인 상세02 "
			+ "	FROM CHARGE_APPROVAL A "
			+ "		, SUBMERCHANT B "
			+ "		, SUBMERCHANT_SERVICE C "
			+ "			WHERE B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "				<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "				<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> "
	        + "		) X "
	        + "		WHERE ROWNUM &lt;= #{offset}+#{limit} "
	        + "	) Z"
	        + "	WHERE RNUM &gt; #{offset} "
	        + "	ORDER BY deal_dt DESC " 
			+ "</script>";
	@Select(GET_CHARGMENTS)
	public List<AccountChargement> getChargments(AccountParam param);
	
	public static final String GET_CHARGMENTS_DAILY_BY_COUNT = "<script> "
			+ "	SELECT count(1)                                                         AS count              "//  -- 총 조회 건수  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN 1 END)       , 0) AS amountCount      "// -- 총 결제 금액  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN 1 END)       , 0) AS cancelCount      "// -- 총 취소 금액 "
			+ " 	, 0 AS refundCount      "// -- 총 환불 금액 "
			+ " 	, NVL(SUM(A.amount)                                              , 0) AS totalSum         "// -- 총 승인 금액 "
			+ "		, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN A.AMOUNT END), 0) AS amountSum        "// -- 총 결제 금액 "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN A.AMOUNT END), 0) AS cancelSum        "// -- 총 취소 금액 "
			+ " 	, 0 AS refundSum        "// -- 총 환불 금액 "
			+ "		, NVL(SUM(A.commision ), 0)               AS billingSum        "//-- 총 정산 금액 "
			+ "	FROM ( "
			+ "		SELECT A.approval_status "
			+ "			,SUM(A.amount) amount "
			+ "			,A.merchant_tax_type "
			+ "			,A.MERCHANT_COMMISION "
			+ " 		,SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') "//-- 비율정산 "
			+ "						THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') "
			+ "						THEN ROUND(((A.amount* -1) * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') "//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') "//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION * -1 "
			+ "						ELSE 0 "
			+ "					END ) commision        "//-- 총 정산 금액 "
			+ "		FROM CHARGE_APPROVAL A "
			+ "			, SUBMERCHANT B "
			+ "			, SUBMERCHANT_SERVICE C "
			+ "		WHERE 1 = 1 "
			+ "		<if test='excelAllFlag != \"\" '> "
	        + "			AND 1 = 2 "
	        + " 	</if>"
	        + "			AND B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "			<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "			<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='serviceNm != \"\" '> "
	        + "				AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + " 		</if> "
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> "
	        + "	GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, A.deal_dt, A.deal_divider, A.charge_method, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION "
	        + "	) A" 
			+ " </script>";
	@Select(GET_CHARGMENTS_DAILY_BY_COUNT)
	public AccountSummaryModel getChargmentsDailyByCount(AccountParam param);
	
	public static final String GET_CHARGMENTS_DAILY = "<script> "
			+ "SELECT Z.* "       
			+ "FROM ( "       
			+ "		SELECT ROWNUM AS RNUM, X.* "
			+ "		FROM ( "
			+ " 		SELECT A.SUBMERCHANT_NM "
			+ " 			,C.name SERVICE_NM "
			+ " 			,A.SVC_CONN_ID "
			+ " 			,A.approval_status "
			+ " 			,FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ " 			,A.charge_method pay_type                              "
			+ " 			,FNC_ADMIN_CODE_TO_NAME(A.charge_method) payTypeName "//-- 지불 수단 "
			+ " 			,A.card_cd "
			+ " 			,FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName "
			+ " 			,A.deal_dt "
			+ " 			,A.deal_divider "
			+ " 			,count(1) cnt "
			+ " 			,SUM(A.amount) amount "
			+ " 			,RTRIM(TO_CHAR(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 "
			+ "	 									THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ " 									WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ " 									THEN A.MERCHANT_COMMISION "
			+ " 									ELSE 0 "
			+ " 								END ),'FM9999999999990.99'),'.') commision "
			+ " 		FROM CHARGE_APPROVAL A "
			+ " 			, SUBMERCHANT B "
			+ " 			, SUBMERCHANT_SERVICE C "
			+ "			WHERE 1 = 1 "
			+ "				AND B.del_flag = 'N' "
			+ "				AND A.submerchant_id = B.submerchant_id "
			+ "				AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "				AND A.submerchant_id = C.submerchant_id(+) "
			+ "				AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "			<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "			<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='serviceNm != \"\" '> "
	        + "				AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + " 		</if> "
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> "
	        + "			GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, A.deal_dt, A.deal_divider, A.charge_method, A.card_cd "
	        + "		) X "
	        + "		WHERE ROWNUM &lt;= #{offset}+#{limit} "
	        + "	) Z"
	        + "	WHERE RNUM &gt; #{offset} "
	        + "	ORDER BY deal_dt DESC " 
			+ "</script>";
	@Select(GET_CHARGMENTS_DAILY)
	public List<AccountApprovalSumm> getChargementsDaily(AccountParam param);
	
	public static final String GET_CHARGMENTS_MONTH_BY_COUNT = "<script> "
			+ "	SELECT count(1)                                                         AS count            "//    -- 총 조회 건수  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN 1 END), 0) AS amountCount    "//   -- 총 결제 금액  "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN 1 END), 0) AS cancelCount    "//   -- 총 취소 금액 "
			+ " 	, 0 AS refundCount    "//   -- 총 환불 금액 "
			+ " 	, NVL(SUM(A.amount)                                              , 0) AS totalSum       "//   -- 총 승인 금액 "
			+ "		, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') THEN A.AMOUNT END), 0) AS amountSum      "//   -- 총 결제 금액 "
			+ " 	, NVL(SUM(CASE WHEN A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') THEN A.AMOUNT END), 0) AS cancelSum      "//   -- 총 취소 금액 "
			+ " 	, 0 AS refundSum      "//   -- 총 환불 금액 "
			+ "		, NVL(SUM(A.commision ), 0)               AS billingSum       "//-- 총 정산 금액 "
			+ "	FROM ( "
			+ "		SELECT A.approval_status "
			+ "			,SUM(A.amount) amount "
			+ "			,A.merchant_tax_type "
			+ "			,A.MERCHANT_COMMISION "
			+ " 		,SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status  = IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009') "//-- 비율정산 "
			+ "						THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' and A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010') "
			+ "						THEN ROUND(((A.amount* -1) * A.MERCHANT_COMMISION) /100,0) "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status = IN ('CHST-0001', 'CHST-0004', 'CHST-0005', 'CHST-0008', 'CHST-0009')"//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION "
			+ "						WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' and A.approval_status IN ('CHST-0002', 'CHST-0003', 'CHST-0006', 'CHST-0007', 'CHST-0010')  "//-- 건당 "
			+ "						THEN A.MERCHANT_COMMISION * -1 "
			+ "						ELSE 0 "
			+ "					END) commision        "//-- 총 정산 금액 "
			+ "		FROM CHARGE_APPROVAL A "
			+ "			, SUBMERCHANT B "
			+ "			, SUBMERCHANT_SERVICE C "
			+ "		WHERE 1 = 1 "
			+ "		<if test='excelAllFlag != \"\" '> "
	        + "			AND 1 = 2 "
	        + " 	</if>"
	        + "			AND B.del_flag = 'N' "
			+ "			AND A.submerchant_id = B.submerchant_id "
			+ "			AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "			AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "			<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "			<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='serviceNm != \"\" '> "
	        + "				AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + " 		</if> "  
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> "
	        + "	GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, SUBSTR(A.deal_dt,1,6), A.deal_divider, A.charge_method, A.card_cd, A.merchant_tax_type, A.MERCHANT_COMMISION "
	        + "	) A" 
			+ " </script>";
	@Select(GET_CHARGMENTS_MONTH_BY_COUNT)
	public AccountSummaryModel getChargementsMonthByCount(AccountParam param);
	
	public static final String GET_CHARGMENTS_MONTH = "<script> "
			+ "SELECT Z.* "       
			+ "FROM ( "       
			+ "		SELECT ROWNUM AS RNUM, X.* "
			+ "		FROM ( "
			+ "			SELECT A.SUBMERCHANT_NM "
			+ "				,c.name SERVICE_NM "
			+ "				,A.SVC_CONN_ID "
			+ "				,A.approval_status "
			+ "				,FNC_ADMIN_CODE_TO_NAME(A.approval_status) approval_status_nm "
			+ "				,A.charge_method pay_type "
			+ "				,FNC_ADMIN_CODE_TO_NAME(A.charge_method) payTypeName "//-- 지불 수단 "
			+ "				,A.card_cd "
			+ "				,FNC_ADMIN_CODE_TO_NAME(A.card_cd) cardCdName "
			+ "				,SUBSTR(A.deal_dt,1,6) deal_dt "
			+ "				,A.deal_divider "
			+ "				,count(1) cnt "
			+ "				,SUM(A.amount) amount "
			+ "				,RTRIM(TO_CHAR(SUM(CASE WHEN A.MERCHANT_COMM_TYPE = 'FEE-0001' "//-- 비율정산 "
			+ "									THEN ROUND((A.amount * A.MERCHANT_COMMISION) /100,0) "
			+ "									WHEN A.MERCHANT_COMM_TYPE = 'FEE-0002' "//-- 건당 "
			+ "									THEN A.MERCHANT_COMMISION "
			+ "									ELSE 0 "
			+ "								END ),'FM9999999999990.99'),'.') commision  "//-- 충전/결제 건만 합산 "
			+ "			FROM CHARGE_APPROVAL A "
			+ " 			, SUBMERCHANT B "
			+ "				, SUBMERCHANT_SERVICE C "
			+ "			WHERE 1 = 1"
			+ "				AND B.del_flag = 'N' "
			+ "				AND A.submerchant_id = B.submerchant_id "
			+ "				AND A.SERVICE_ID = C.SERVICE_ID(+) "
			+ "				AND A.submerchant_id = C.submerchant_id(+) "
			+ "			AND A.DEAL_DIVIDER = 'DAYT-0001' "
			+ "			<if test='dateType==\"DAYT-0001\"'> AND A.deal_dt BETWEEN #{startDate} AND #{endDate} </if>"
			+ "			<if test='dateType==\"DAYT-0002\"'> AND A.approval_Dt BETWEEN TO_DATE(#{startDate}||'000000', 'yyyymmddhh24miss') AND TO_DATE(#{endDate}||'235959', 'yyyymmddhh24miss') </if>"
			+ " 		<if test='merchantId != \"\" '> "
	        + "				AND A.submerchant_id = #{merchantId} "
	        + " 		</if> "  
	        + " 		<if test='serviceNm != \"\" '> "
	        + "				AND C.name LIKE '%' || #{serviceNm} || '%' "
	        + " 		</if> " 
	        + " 		<if test='approvalStatus != \"\" and approvalStatus != \"all\" '> "
	        + "				AND A.approval_status IN "
	        + " 			<foreach collection='approvalStatusList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> " 
	        + " 		<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + " 		</if> "
	        + " 		<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + " 		</if> "
	        + " 		<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + " 		</if> "
	        + " 		<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + " 		</if> "
	        + " 		<if test='payMethod != \"\" and payMethod != \"all\" '> "
	        + "				AND A.charge_method IN "
	        + " 			<foreach collection='payMethods' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach>"
	        + " 		</if> "
	        + " 		<if test='saleDivider != \"\" '> "
	        + "				AND C.sale_divider = #{saleDivider} "
	        + " 		</if> "
	        + " 		<if test='cardType != \"\" and cardType != \"all\" '> "
	        + "				AND A.card_cd IN "
	        + " 			<foreach collection='cardTypeList' item='item' index='index' separator=',' open='(' close=')' >"
    		+ "		   			#{item} "
    		+ "				</foreach> "
	        + " 		</if> "
	        + "		GROUP BY A.SUBMERCHANT_NM , C.name ,A.SVC_CONN_ID, A.approval_status, SUBSTR(A.deal_dt,1,6), A.deal_divider, A.charge_method, A.card_cd "
	        + "		) X "
	        + "		WHERE ROWNUM &lt;= #{offset}+#{limit} "
	        + "	) Z"
	        + "	WHERE RNUM &gt; #{offset} "
			+ "</script>";
	@Select(GET_CHARGMENTS_MONTH)
	public List<AccountApprovalSumm> getChargementMonth(AccountParam param);
	
	public static final String GET_SALEMENTS_BY_COUNT = "<script> "
			+ "	SELECT count(1) AS count "
			+ "		, NVL(SUM(DECODE(A.approval_status, 'SSTS-0001', 1 , 0)), 0) AS amountCount "
			+ "		, NVL(SUM(DECODE(A.approval_status, 'SSTS-0002', 1 , 0)), 0) AS cancelCount "
			+ "		, 0 AS refundCount "
			+ "		, NVL(SUM(A.SALE_AMT * A.SALE_CNT), 0) AS totalSum "
			+ "		, NVL(SUM(DECODE(A.approval_status, 'SSTS-0001', A.SALE_AMT * A.SALE_CNT, 0)), 0) AS amountSum "
			+ "		, NVL(SUM(DECODE(A.approval_status, 'SSTS-0002', A.SALE_AMT * A.SALE_CNT, 0)), 0) AS cancelSum "
			+ "		, 0 AS refundSum "
			+ "		, 0 AS billingSum "
			+ "	FROM SALE_APPROVAL A "
			+ "		, SUBMERCHANT B "
			+ "		, SUBMERCHANT_SERVICE C "
            + "	WHERE 1 = 1 "
            + " 	AND B.del_flag = 'N' "
            + "		AND A.submerchant_id = B.submerchant_id "
            + "		AND A.SERVICE_ID = C.SERVICE_ID(+) "
            + "		AND A.submerchant_id = C.submerchant_id(+) "
			+ "		AND A.deal_dt BETWEEN #{startDate} AND #{endDate}"
            + "	<if test='excelAllFlag != \"\" '> "
	        + "		AND 1 = 2 "
	        + "	</if> "  
	        + "	<if test='merchantNm != \"\" '> "
	        + "		AND A.submerchant_nm LIKE '%' || #{merchantNm} || '%' "
	        + "	</if> "
	        + "	<if test='merchantId != \"\" '> "
	        + "		AND C.name LIKE '%' || #{merchantId} || '%' "
	        + "	</if> "
	        + "	<if test='serviceId != \"\" '> "
	        + "		AND A.service_id = #{serviceId} "
	        + "	</if> "
	        + "	<if test='approvalNo != \"\" '> "
	        + "		AND A.approval_no = #{approvalNo} "
	        + "	</if> "
	        + "	<if test='orderNo != \"\" '> "
	        + "		AND A.order_no = #{orderNo} "
	        + "	</if> "
	        + "	<if test='prodType != \"\" '> "
	        + "		AND A.prod_type = #{prodType} "
	        + "	</if> "
	        + "	<if test='saleMethod != \"\" '> "
	        + "		AND A.sale_method = #{saleMethod} "
	        + "	</if> "
	        + "	<if test='svcConnId != \"\" '> "
	        + "		AND A.svc_conn_id = #{svcConnId} "
	        + "	</if> "
	        + "	<if test='amount != \"\" '> "
	        + "		AND A.sale_amt = #{amount} "
	        + "	</if> "
	        + "	<if test='approvalStatus != \"\" '> "
	        + "		AND A.approval_status = #{approvalStatus} "
	        + "	</if> "
			+ " </script>";
	@Select(GET_SALEMENTS_BY_COUNT)
	public AccountSummaryModel getSalementsByCount(AccountSalementParam param);
	
	public static final String GET_SALEMENTS = "<script> "
			+ " SELECT Z.* "
			+ "	FROM ( "
			+ "		SELECT ROWNUM AS RNUM, X.* "
			+ "		FROM ( "
			+ "			SELECT A.SEQ                   seq                         "//-- 판매 승인 시퀀스 "
			+ "				, A.SUMM_SEQ              summSeq                     "//-- 판매 승인 요약 시퀀스 "
			+ "				, A.SUBMERCHANT_ID        submerchantId               "//-- 거래처 아이디 "
			+ "				, A.SUBMERCHANT_NM        submerchantNm               "//-- 거래처명 "
			+ "				, A.SERVICE_ID            serviceId                   "//-- 서비스 시퀀스 "
			+ "				, C.name                  serviceNm                   "//-- 서비스명 "
			+ "				, A.SERVICE_TYPE          serviceType                 "//-- 서비스타입 "
			+ "				, A.SERVICE_CATEGORY      serviceCategory             "//-- 서비스 카테고리 "
			+ "				, A.SVC_CONN_ID           svcConnId                   "//-- 서비스연동아이디 "
			+ "				, A.DEAL_DIVIDER          dealDivider                 "//-- 거래 구분(거래일/영업일) "
			+ "				, A.DEAL_DT               dealDt                      "//-- 거래 구분 일(거래일/영업일) "
			+ "				, A.APPROVAL_DT           approvalDt                  "//-- 승인일시 "
			+ "				, A.APPROVAL_STATUS       approvalStatus              "//-- 승인상태(판매/취소) "
			+ "				, FNC_ADMIN_CODE_TO_NAME(A.APPROVAL_STATUS) approvalStatusNm            "//-- 승인상태명(판매/취소) "
			+ "				, A.APPROVAL_NO           approvalNo                  "//-- 승인번호 "
			+ "				, A.ORDER_NO              orderNo                     "//-- 주문번호  "
			+ "				, A.PROD_TYPE             prodType                    "//-- 상품(쿠폰) 타입 "
			+ "				, FNC_ADMIN_CODE_TO_NAME(A.PROD_TYPE) prodTypeNm      "//-- 상품(쿠폰) 타입 명 "
			+ "				, A.PROD_CD               prodCd                      "//-- 상품(쿠폰) 코드 "
			+ "				, A.PROD_NM               prodNm                      "//-- 상품(쿠폰) 명 "
			+ "				, A.SALE_CNT              saleCnt                     "//-- (판매) 금액 "
			+ "				, A.SALE_AMT              saleAmt                     "//-- (판매) 금액 "
			+ "				, A.SALE_TYPE             saleType                    "//-- 판매 타입 "
			+ "				, A.SALE_METHOD           saleMethod                  "//-- 판매 수단 "
			+ "				, FNC_ADMIN_CODE_TO_NAME(A.SALE_METHOD) saleMethodName              "//-- 판매 수단 명 "
			+ "				, A.STORE_CD              storeCd                     "//-- 매장(점포) 코드 "
			+ "				, A.STORE_NM              storeNm                     "//-- 매장(점포) 이름 "
			+ "				, A.POS_NO                posNo                       "//-- 매장(점포) POS No "
			+ "				, A.CP_ID                 cpId                        "//-- CP ID "
			+ "				, A.CP_USER_ID            cpUserId                    "//-- CP User ID "
			+ "				, A.CP_USER_IP            cpUserIp                    "//-- CP User IP "
			+ "				, A.MERCHANT_COMM_TYPE    merchantCommType            "//-- 거래처수수료타입 "
			+ "				, A.MERCHANT_COMMISION    merchantCommision           "//-- 거래처 수수료 "
			+ "				, A.MERCHANT_TAX_TYPE     merchantTaxType             "//-- 거래처부가세타입 "
			+ "				, A.MERCHANT_TAX          merchantTax                 "//-- 거래처 부가세 "
			+ "				, A.KPC_COMM_TYPE         kpcCommType                 "//-- KPC수수료타입 "
			+ "				, A.KPC_COMMISION         kpcCommision                "//-- KPC 수수료 "
			+ "				, A.KPC_TAX_TYPE          kpcTax_type                 "//-- KPC부가세타입 "
			+ "				, A.KPC_TAX               kpcTax                      "//-- KPC 부가세 "
			+ "				, A.ADD_COMM_TYPE01       addCommType01               "//-- 추가 수수료타입01 "
			+ "				, A.ADD_COMMISION01       addCommision01              "//-- 부가 수수료 01 "
			+ "				, A.ADD_TAX_TYPE01        addTaxType01                "//-- 추가 부가세타입01 "
			+ "				, A.ADD_TAX01             addTax01                    "//-- 부가 부가세 01 "
			+ "				, A.ADD_COMM_TYPE02       addCommType02               "//-- 추가 수수료타입02 "
			+ "				, A.ADD_COMMISION02       addCommision02              "//-- 부가 수수료 02 "
			+ "				, A.ADD_TAX_TYPE02        addTaxType02                "//-- 추가 부가세타입02 "
			+ "				, A.ADD_TAX02             addTax02                    "//-- 부가 부가세 02 "
			+ "				, A.BILLING_SUM           billingSum                  "//-- 정산 금액 "
			+ "				, A.DESC01                desc01                      "//-- 승인 상세01 "
			+ "				, A.DESC02                desc02                      "//-- 승인 상세02 "
			+ "			FROM SALE_APPROVAL A "
			+ "				, SUBMERCHANT B "
			+ "				, SUBMERCHANT_SERVICE C "
			+ "			WHERE 1 = 1 "
			+ "				AND B.del_flag           = 'N' "
			+ "				AND A.submerchant_id     = B.submerchant_id "
			+ "				AND A.submerchant_id     = C.submerchant_id(+) "
			+ "				AND A.SERVICE_ID         = C.SERVICE_ID(+) "
			+ "				AND A.deal_dt BETWEEN #{startDate} AND #{endDate}"
	        + "			<if test='merchantNm != \"\" '> "
	        + "				AND A.submerchant_nm LIKE '%' || #{merchantNm} || '%' "
	        + "			</if> "
	        + "			<if test='merchantId != \"\" '> "
	        + "				AND C.name LIKE '%' || #{merchantId} || '%' "
	        + "			</if> "
	        + "			<if test='serviceId != \"\" '> "
	        + "				AND A.service_id = #{serviceId} "
	        + "			</if> "
	        + "			<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + "			</if> "
	        + "			<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + "			</if> "
	        + "			<if test='prodType != \"\" '> "
	        + "				AND A.prod_type = #{prodType} "
	        + "			</if> "
	        + "			<if test='saleMethod != \"\" '> "
	        + "				AND A.sale_method = #{saleMethod} "
	        + "			</if> "
	        + "			<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId} "
	        + "			</if> "
	        + "			<if test='amount != \"\" '> "
	        + "				AND A.sale_amt = #{amount} "
	        + "			</if> "
	        + "			<if test='approvalStatus != \"\" '> "
	        + "				AND A.approval_status = #{approvalStatus} "
	        + "			</if>"
			+ "		) X "
			+ "		WHERE ROWNUM &lt;= (#{offset} + #{limit}) "
			+ "	) Z "
			+ "	WHERE RNUM &gt; #{offset} "
			+ "</script>";
	@Select(GET_SALEMENTS)
	public List<AccountSalement> getsalements(AccountSalementParam param);
	
	public static final String GET_SALEMENTS_MONTH_BY_COUNT = "<script> "
			+ "	SELECT count(1) AS count "
			+ "		, NVL(SUM(DECODE(A.approval_status, 'SSTS-0001', 1 , 0)), 0) AS amountCount "
			+ " 	, NVL(SUM(DECODE(A.approval_status, 'SSTS-0002', 1, 0)), 0) AS cancelCount "
			+ " 	, 0 AS refundCount "
			+ " 	, NVL(SUM(A.SALE_AMT * A.SALE_CNT)                               , 0)   AS totalSum "
			+ " 	, NVL(SUM(DECODE(A.approval_status, 'SSTS-0001', A.SALE_AMT * A.SALE_CNT, 0)), 0) AS amountSum "
			+ " 	, NVL(SUM(DECODE(A.approval_status, 'SSTS-0002', A.SALE_AMT * A.SALE_CNT, 0)), 0) AS cancelSum "
			+ " 	, 0 AS refundSum "
			+ " 	, 0 AS billingSum "
			+ "	FROM ( "
			+ "		SELECT A.approval_status "
			+ "			,A.SALE_AMT "
			+ "			,SUM(A.SALE_CNT) SALE_CNT "
			+ "		FROM SALE_APPROVAL A "
			+ "			, SUBMERCHANT B "
			+ "			, SUBMERCHANT_SERVICE C "
			+ "		WHERE 1 = 1 "
			+ "			AND B.del_flag           = 'N' "
			+ "			AND A.submerchant_id     = B.submerchant_id "
			+ "			AND A.submerchant_id     = C.submerchant_id(+) "
			+ "			AND A.SERVICE_ID         = C.SERVICE_ID(+) "
			+ "			AND A.deal_dt BETWEEN #{startDate} AND #{endDate}"
            + "		<if test='excelAllFlag != \"\" '> "
	        + "		AND 1 = 2 "
	        + "		</if> " 
			+ "		<if test='merchantNm != \"\" '> "
	        + "			AND A.submerchant_nm LIKE '%' || #{merchantNm} || '%' "
	        + "		</if> "
	        + "		<if test='merchantId != \"\" '> "
	        + "			AND C.name LIKE '%' || #{merchantId} || '%' "
	        + "		</if> "
	        + "		<if test='serviceId != \"\" '> "
	        + "			AND A.service_id LIKE '%' || #{serviceId} || '%'"
	        + "		</if> "
	        + "		<if test='approvalNo != \"\" '> "
	        + "			AND A.approval_no = #{approvalNo} "
	        + "		</if> "
	        + "		<if test='orderNo != \"\" '> "
	        + "			AND A.order_no = #{orderNo} "
	        + "		</if> "
	        + "		<if test='prodType != \"\" '> "
	        + "			AND A.prod_type = #{prodType} "
	        + "		</if> "
	        + "		<if test='saleMethod != \"\" '> "
	        + "			AND A.sale_method = #{saleMethod} "
	        + "		</if> "
	        + "		<if test='svcConnId != \"\" '> "
	        + "			AND A.svc_conn_id LIKE '%' || #{svcConnId} || '%'"
	        + "		</if> "
	        + "		<if test='amount != \"\" '> "
	        + "			AND A.sale_amt = #{amount} "
	        + "		</if> "
	        + "		<if test='approvalStatus != \"\" '> "
	        + "			AND A.approval_status = #{approvalStatus} "
	        + "		</if> "
	        + "		GROUP BY A.SUBMERCHANT_NM "
			+ "			, C.name "
			+ "			, A.SVC_CONN_ID "
			+ "			, A.approval_status "
			+ "			, SUBSTR(A.deal_dt,1,6) "
			+ "			, A.SALE_AMT "
			+ "			, A.PROD_NM " 
			+ "			, A.PROD_CD "
			+ "			, A.PROD_TYPE "   
			+ "	) A "
			+ " </script>";
	@Select(GET_SALEMENTS_MONTH_BY_COUNT)
	public AccountSummaryModel getSalementsMothByCount(AccountSalementParam param);
	
	public static final String GET_SALEMENTS_MONTH = "<script> "
			+ " SELECT Z.* "
			+ "	FROM ( "
			+ " 	SELECT ROWNUM AS RNUM, X.* "
			+ " 	FROM ( "
			+ " 		SELECT A.SUBMERCHANT_NM                              submerchantNm "                                
			+ " 			,C.name                                        serviceNm "
			+ " 			,A.SVC_CONN_ID                                 svcConnId "                                  
			+ " 			,A.approval_status                             approvalStatus "                                
			+ " 			,FNC_ADMIN_CODE_TO_NAME(A.approval_status)     approvalStatusNm "
			+ " 			,A.PROD_NM                                     prodNm "
			+ " 			,A.PROD_CD                                     prodCd "
			+ " 			,FNC_ADMIN_CODE_TO_NAME(A.PROD_TYPE)           prodTypeNm "
			+ " 			,SUBSTR(A.deal_dt,1,6)                         dealDt "
			+ " 			,A.SALE_AMT                                    saleAmt "
			+ " 			,SUM(A.SALE_CNT)                               saleCnt "
			+ " 			,count(1)                                      cnt "
			+ " 		FROM SALE_APPROVAL    A "
			+ " 			, SUBMERCHANT     B "
			+ " 			, SUBMERCHANT_SERVICE C "
			+ " 		WHERE 1 = 1 "
			+ " 			AND B.del_flag           = 'N' "
			+ " 			AND A.submerchant_id     = B.submerchant_id "
			+ " 			AND A.submerchant_id     = C.submerchant_id(+) "
			+ " 			AND A.SERVICE_ID         = C.SERVICE_ID(+) "
			+ "				AND A.deal_dt BETWEEN #{startDate} AND #{endDate}"
			+ "			<if test='merchantNm != \"\" '> "
	        + "				AND A.submerchant_nm LIKE '%' || #{merchantNm} || '%' "
	        + "			</if> "
	        + "			<if test='merchantId != \"\" '> "
	        + "				AND C.name LIKE '%' || #{merchantId} || '%' "
	        + "			</if> "
	        + "			<if test='serviceId != \"\" '> "
	        + "				AND A.service_id LIKE '%' || #{serviceId} || '%'"
	        + "			</if> "
	        + "			<if test='approvalNo != \"\" '> "
	        + "				AND A.approval_no = #{approvalNo} "
	        + "			</if> "
	        + "			<if test='orderNo != \"\" '> "
	        + "				AND A.order_no = #{orderNo} "
	        + "			</if> "
	        + "			<if test='prodType != \"\" '> "
	        + "				AND A.prod_type = #{prodType} "
	        + "			</if> "
	        + "			<if test='saleMethod != \"\" '> "
	        + "				AND A.sale_method = #{saleMethod} "
	        + "			</if> "
	        + "			<if test='svcConnId != \"\" '> "
	        + "				AND A.svc_conn_id = #{svcConnId}"
	        + "			</if> "
	        + "			<if test='amount != \"\" '> "
	        + "				AND A.sale_amt = #{amount} "
	        + "			</if> "
	        + "			<if test='approvalStatus != \"\" '> "
	        + "				AND A.approval_status = #{approvalStatus} "
	        + "			</if> "
	        + "			GROUP BY A.SUBMERCHANT_NM " 
			+ "				, C.name "
			+ "				, A.SVC_CONN_ID "
			+ "				, A.approval_status "
			+ "				, SUBSTR(A.deal_dt,1,6) "
			+ "				, A.SALE_AMT "
			+ "				, A.PROD_NM "
			+ "				, A.PROD_CD "
			+ "				, A.PROD_TYPE "
			+ "		) X "
			+ "		WHERE ROWNUM &lt;= (#{offset} + #{limit}) "
			+ "	) Z "
			+ "	WHERE RNUM &gt; #{offset}"	        
			+ "</script>";
	@Select(GET_SALEMENTS_MONTH)
	public List<AccountSalementSumm> getSalementsMonth(AccountSalementParam param);
}
