package kr.co.kpcard.backoffice.repository.approval.model;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
@Deprecated
public interface ApprovalMerchantMapper {

	public static final String CREATE_MERCHANT_TMP_SEQ = "SELECT NVL(MAX(SEQ),0) + 1 SEQ FROM MERCHANT_TMP";
	@Select(CREATE_MERCHANT_TMP_SEQ)
	public String createMerchantTmpSeq();
	
	public static final String INSERT_MERCHANT_TMP = "INSERT INTO MERCHANT_TMP( "
			+ " 	SEQ "
			+ " 	,MERCHANT_ID "
			+ " 	,NAME "
			+ " 	,ALIAS "
			+ " 	,USE_FLAG "
			+ " 	,DEL_FLAG "
			+ " 	,CREATE_DT "
			+ " 	,CREATE_DESC "
			+ " 	,BIZ_KIND "
			+ " 	,BIZ_COND "
			+ " 	,BIZ_GRP "
			+ " 	,CORP_REG_NO "
			+ " 	,BIZ_REG_NO "
			+ " 	,OPEN_DT "
			+ " 	,CEO_NM "
			+ " 	,ZIPCODE "
			+ " 	,ADDRESS "
			+ " 	,ADDRESS_DTL "
			+ " 	,TEL "
			+ " 	,FAX "
			+ " ) VALUES ( "
			+ " 	#{tmpSeq} "
			+ " 	,#{merchantId} "
			+ " 	,#{name} "
			+ " 	,#{alias} "
			+ " 	,#{useFlag} "
			+ " 	,'N' "
			+ " 	,SYSDATE "
			+ " 	,#{createDesc} "
			+ " 	,#{bizKind} "
			+ " 	,#{bizCond} "
			+ " 	,#{bizGrp} "
			+ " 	,#{corpRegNo} "
			+ " 	,#{bizRegNo} "
			+ " 	,#{openDate} "
			+ " 	,#{ceoName} "
			+ " 	,#{zipcode} "
			+ " 	,#{address} "
			+ " 	,#{addressDetail} "
			+ " 	,#{tel} "
			+ " 	,#{fax} "
			+ " )";
	@Insert(INSERT_MERCHANT_TMP)
	public int insertMerchantTmp(
			@Param(value="tmpSeq") String tmpSeq, @Param(value="merchantId") String merchantId, @Param(value="name") String name, @Param(value="alias") String alias, @Param(value="useFlag") String useFlag,
			@Param(value="createDesc") String createDesc, @Param(value="bizKind") String bizKind, @Param(value="bizCond") String bizCond, @Param(value="bizGrp") String bizGrp, @Param(value="corpRegNo") String corpRegNo, 
			@Param(value="bizRegNo") String bizRegNo, @Param(value="openDate") String openDate, @Param(value="ceoName") String ceoName, @Param(value="zipcode") String zipcode, @Param(value="address") String address,
			@Param(value="addressDetail") String addressDetail, @Param(value="tel") String tel, @Param(value="fax") String fax);
	
	public static final String UPDATE_MERCHANT_TMP = "UPDATE MERCHANT_TMP "
            + " 	SET NAME           = #{name}                       "
            + " 	   ,ALIAS          = #{alias}                      "
            + " 	   ,USE_FLAG       = #{useFlag}                    "
            + " 	   ,DEL_FLAG       = 'N'                                 "
            + " 	   ,CREATE_DT      = SYSDATE                             "
            + " 	   ,CREATE_DESC    = #{createDesc}                 "
            + " 	   ,BIZ_KIND       = #{bizKind}                    "
            + " 	   ,BIZ_COND       = #{bizCond}                    "
            + " 	   ,BIZ_GRP        = #{bizGrp}                     "
            + " 	   ,CORP_REG_NO    = #{corpRegNo}                  "
            + " 	   ,BIZ_REG_NO     = #{bizRegNo}                   "
            + " 	   ,OPEN_DT        = #{openDt}                     "
            + " 	   ,CEO_NM         = #{ceoNm}                      "
            + " 	   ,ZIPCODE        = #{zipcode}                    "
            + " 	   ,ADDRESS        = #{address}                    "
            + " 	   ,ADDRESS_DTL    = #{addressDtl}                 "
            + " 	   ,TEL            = #{tel}                        "
            + " 	   ,FAX            = #{fax}                        "
            + " WHERE SEQ = #{tmpSeq}                              "
            + " 	AND '1' = ( SELECT '1'                                   "
            + "     	          FROM KPC_EL_APPR                           "
            + "         	     WHERE SEQ        = #{seq}             "
            + "             	   AND REQ_EMP_ID = #{reqEmpId})";
	@Update(UPDATE_MERCHANT_TMP)
	public int updateMerchantTmp(@Param(value="name") String name, @Param(value="alias") String alias,
			@Param(value="useFlag") String useFlag, @Param(value="createDesc") String createDesc,
			@Param(value="bizKind") String bizKind, @Param(value="bizCond") String bizCond, 
			@Param(value="bizGrp") String bizGrp, @Param(value="corpRegNo") String corpRegNo, 
			@Param(value="bizRegNo") String bizRegNo, @Param(value="openDt") String openDt,
			@Param(value="ceoNm") String ceoNm, @Param(value="zipcode") String zipcode, 
			@Param(value="address") String address, @Param(value="addressDtl") String addressDtl,
			@Param(value="tel") String tel, @Param(value="fax") String fax,
			@Param(value="tmpSeq") String tmpSeq, @Param(value="seq") String seq,
			@Param(value="reqEmpId") String reqEmpId);
	
	
	public static final String INSERT_SUBMERCHANT_TMP = "INSERT INTO SUBMERCHANT_TMP( "
			+ " 	SEQ "
			+ " 	,submerchant_id "
			+ " 	,depth "
			+ " 	,parent_id "
			+ " 	,name "
			+ " 	,alias "
			+ " 	,use_flag "
			+ " 	,del_flag "
			+ " 	,agent_id "
			+ " 	,agent_pw "
			+ " 	,create_dt "
			+ " 	,create_desc "
			+ " 	,biz_kind "
			+ " 	,biz_cond "
			+ " 	,corp_reg_no "
			+ " 	,biz_reg_no "
			+ " 	,ceo_nm "
			+ " 	,type "
			+ " 	,open_dt "
			+ " 	,bank_nm "
			+ " 	,bank_acc_no "
			+ " 	,bank_holder "
			+ " 	,zipcode "
			+ " 	,address "
			+ " 	,address_dtl "
			+ " 	,tel "
			+ " 	,fax "
			+ " 	,tax_cust_nm "
			+ " 	,tax_email "
			+ " 	,tax_tel "
			+ " 	,tax_phone "
			+ " 	,tax_fax "
			+ " 	,sales_nm "
			+ " 	,sales_tel "
			+ " 	,billing_nm "
			+ " 	,billing_tel "
			+ " 	,kpc_sales_nm "
			+ " 	,kpc_sales_tel "
			+ " 	,kpc_billing_nm "
			+ "		,kpc_billing_tel "
			+ " 	,url_home "
			+ " ) VALUES ( "
			+ " 	#{tmpSeq} "
			+ " 	,#{subMerchantId} "
			+ " 	,(SELECT NVL(MAX(depth),0) + 1 " 
			+ " 		FROM submerchant "
			+ " 		WHERE parent_id = #{parentId} "
			+ " 	) "
			+ " 	,#{parentId} "
			+ " 	,#{name} "
			+ " 	,#{alias} "
			+ " 	,#{useFlag} "
			+ " 	,'N' "
			+ " 	,#{agentId} "
			+ " 	,#{agentPw} "
			+ " 	,SYSDATE "
			+ " 	,'신규등록' "
			+ " 	,#{bizKind} "
			+ " 	,#{bizCond} "
			+ " 	,#{corpRegNo} "
			+ " 	,#{bizRegNo} "
			+ " 	,#{ceoName} "
			+ " 	,#{bizGrp} "
			+ " 	,#{openDate} "
			+ " 	,#{bankNm} "
			+ " 	,#{bankAccNo} "
			+ " 	,#{bankHolder} "
			+ " 	,#{zipcode} "
			+ " 	,#{address} "
			+ " 	,#{addressDetail} "
			+ " 	,#{tel} "
			+ " 	,#{fax} "
			+ " 	,#{taxCustName} "
			+ " 	,#{taxEmail} "
			+ " 	,#{taxTel} "
			+ " 	,#{taxPhone} "
			+ " 	,#{taxFax} "
			+ " 	,#{salesNm} "
			+ " 	,#{salesTel} "
			+ " 	,#{billingNm} "
			+ " 	,#{billingTel} "
			+ " 	,#{kpcSalesNm} "
			+ " 	,#{kpcSalesTel} "
			+ " 	,#{kpcBillingNm} "
			+ " 	,#{kpcBillingTel} "
			+ " 	,#{urlHome} " 
			+ " ) ";
	@Insert(INSERT_SUBMERCHANT_TMP)
	public int insertSubMerchantTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="subMerchantId") String subMerchantId,
			@Param(value="parentId") String parentId, @Param(value="name") String name, @Param(value="alias") String alias,
			@Param(value="useFlag") String useFlag, @Param(value="agentId") String agentId, @Param(value="agentPw") String agentPw,
			@Param(value="bizKind") String bizKind, @Param(value="bizCond") String bizCond, @Param(value="corpRegNo") String corpRegNo, 
			@Param(value="bizRegNo") String bizRegNo, @Param(value="ceoName") String ceoName, @Param(value="bizGrp") String bizGrp, 
			@Param(value="openDate") String openDate, @Param(value="bankNm") String bankNm, @Param(value="bankAccNo") String bankAccNo, 
			@Param(value="bankHolder") String bankHolder, @Param(value="zipcode") String zipcode, @Param(value="address") String address, 
			@Param(value="addressDetail") String addressDetail, @Param(value="tel") String tel, @Param(value="fax") String fax, 
			@Param(value="taxCustName") String taxCustName, @Param(value="taxTel") String taxTel, @Param(value="taxFax") String taxFax, 
			@Param(value="taxPhone") String taxPhone, @Param(value="taxEmail") String taxEmail,  @Param(value="salesNm") String salesNm, 
			@Param(value="salesTel") String salesTel, @Param(value="billingNm") String billingNm, @Param(value="billingTel") String billingTel, 
			@Param(value="kpcSalesNm") String kpcSalesNm, @Param(value="kpcSalesTel") String kpcSalesTel, @Param(value="kpcBillingNm") String kpcBillingNm, 
			@Param(value="kpcBillingTel")String kpcBillingTel, @Param(value="urlHome") String urlHome);
	
	public static final String UPDATE_SUBMERCHANT_TMP = "UPDATE SUBMERCHANT_TMP          "
	        + "      SET name            = #{name}                   "
	        + "         ,alias           = #{alias}                  "
	        + "         ,use_flag        = #{useFlag}                "
	        + "         ,agent_id        = #{agentId}                "
	        + "         ,agent_pw        = #{updateAgentPw}                              "
	        + "         ,update_dt       = SYSDATE                                       "
	        + "         ,update_desc     = '수정'                                        "
	        + "         ,biz_kind        = #{bizKind}                "
	        + "         ,biz_cond        = #{bizCond}                "
	        + "         ,corp_reg_no     = #{corpRegNo}              "
	        + "         ,biz_reg_no      = #{bizRegNo}               "
	        + "         ,ceo_nm          = #{ceoName}                "
	        + "         ,type            = #{bizGrp}                 "
	        + "         ,open_dt         = #{openDate}               "
	        + "         ,bank_nm         = #{bankNm}                 "
	        + "         ,bank_acc_no     = #{bankAccNo}              "
	        + "         ,bank_holder     = #{bankHolder}             "
	        + "         ,zipcode         = #{zipcode}                "
	        + "         ,address         = #{address}                "
	        + "         ,address_dtl     = #{addressDetail}          "
	        + "         ,tel             = #{tel}                    "
	        + "         ,fax             = #{fax}                    "
	        + "         ,tax_cust_nm     = #{taxCustName}            "
	        + "         ,tax_email       = #{taxEmail}               "
	        + "         ,tax_tel         = #{taxTel}                 "
	        + "         ,tax_phone       = #{taxPhone}               "
	        + "         ,tax_fax         = #{taxFax}                 "
	        + "         ,sales_nm        = #{salesNm}                "
	        + "         ,sales_tel       = #{salesTel}               "
	        + "         ,billing_nm      = #{billingNm}              "
	        + "         ,billing_tel     = #{billingTel}             "
	        + "         ,kpc_sales_nm    = #{kpcSalesNm}             "
	        + "         ,kpc_sales_tel   = #{kpcSalesTel}            "
	        + "         ,kpc_billing_nm  = #{kpcBillingNm}           "
	        + "         ,kpc_billing_tel = #{kpcBillingTel}          "
	        + "         ,url_home        = #{urlHome}                "
	        + "   WHERE SEQ              = #{tmpSeq}              "
	        + "     AND '1' = ( SELECT '1'                                               "
	        + "                   FROM KPC_EL_APPR                                       "
	        + "                  WHERE SEQ        = #{seq}        "
	        + "                    AND REQ_EMP_ID = #{reqEmpId})  ";
	@Update(UPDATE_SUBMERCHANT_TMP)
	public int updateSubMerchantTmp(@Param(value="name") String name, @Param(value="alias") String alias,
			@Param(value="useFlag") String useFlag, @Param(value="agentId") String agentId, @Param(value="agentPw") String agentPw,
			@Param(value="bizKind") String bizKind, @Param(value="bizCond") String bizCond, @Param(value="corpRegNo") String corpRegNo, 
			@Param(value="bizRegNo") String bizRegNo, @Param(value="ceoName") String ceoName, @Param(value="bizGrp") String bizGrp, 
			@Param(value="openDate") String openDate, @Param(value="bankNm") String bankNm, @Param(value="bankAccNo") String bankAccNo, 
			@Param(value="bankHolder") String bankHolder, @Param(value="zipcode") String zipcode, @Param(value="address") String address, 
			@Param(value="addressDetail") String addressDetail, @Param(value="tel") String tel, @Param(value="fax") String fax, 
			@Param(value="taxCustName") String taxCustName, @Param(value="taxTel") String taxTel, @Param(value="taxFax") String taxFax, 
			@Param(value="taxPhone") String taxPhone, @Param(value="taxEmail") String taxEmail,  @Param(value="salesNm") String salesNm, 
			@Param(value="salesTel") String salesTel, @Param(value="billingNm") String billingNm, @Param(value="billingTel") String billingTel, 
			@Param(value="kpcSalesNm") String kpcSalesNm, @Param(value="kpcSalesTel") String kpcSalesTel, @Param(value="kpcBillingNm") String kpcBillingNm, 
			@Param(value="kpcBillingTel")String kpcBillingTel, @Param(value="urlHome") String urlHome,
			@Param(value="updateAgentPw")String updateAgentPw, @Param(value="tmpSeq") String tmpSeq, @Param(value="seq")String seq, 
			@Param(value="reqEmpId") String reqEmpId);
	
	public static final String INSERT_SUBMERCHANT_SERVICE_TMP = "INSERT INTO SUBMERCHANT_SERVICE_TMP( "
			+ " 	SEQ "
			+ " 	,service_id "
			+ " 	,submerchant_id "
			+ " 	,name "
			+ " 	,category "
			+ " 	,type "
			+ " 	,use_flag "
			+ " 	,del_flag "
			+ " 	,svc_conn_id "
			+ " 	,svc_conn_pw "
			+ " 	,sale_divider "
			+ " 	,create_dt "
			+ " 	,create_desc "
			+ " 	,create_adm_id "
			+ " ) VALUES ( "
			+ " 	#{tmpSeq} "
			+ " 	,#{serviceId} "
			+ " 	,#{subMerchantId} "
			+ " 	,#{serviceName  } "
			+ " 	,#{category     } "
			+ " 	,#{serviceType  } "
			+ " 	,#{useFlag      } "
			+ " 	,'N' "
			+ " 	,#{svcConnId    } "
			+ " 	,#{svcConnPw    } "
			+ " 	,#{saleDivider  } "
			+ " 	,SYSDATE "
			+ " 	,#{createDesc   } "
			+ " 	,#{createAdmId  } "
			+ " ) ";
	@Insert(INSERT_SUBMERCHANT_SERVICE_TMP)
	public int insertSubMerchantServiceTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="serviceId") String serviceId, @Param(value="subMerchantId") String subMerchantId,
			@Param(value="serviceName") String serviceName, @Param(value="category") String category, @Param(value="serviceType") String serviceType,
			@Param(value="useFlag") String useFlag, @Param(value="svcConnId") String svcConnId, @Param(value="svcConnPw") String svcConnPw,
			@Param(value="saleDivider") String saleDivider, @Param(value="createDesc") String createDesc, @Param(value="createAdmId") String createAdmId);
	
	public static final String UPDATE_SUBMERCHANT_SERVICE_TMP = "UPDATE SUBMERCHANT_SERVICE_TMP "
	        + "      SET CATEGORY      = #{category    }                                 "
	        + "        , NAME          = #{name        }                                 "
	        + "        , TYPE          = #{serviceType }                                 "
	        + "        , USE_FLAG      = #{useFlag     }                                 "
	  	    + "        , SALE_DIVIDER  = #{saleDivider }                                 "
	        + "        , SVC_CONN_ID   = #{svcConnId   }                                 "
	        + "        , SVC_CONN_PW   = #{svcConnPw   }                                 "
	        + "        , UPDATE_DESC   = '수정'                                                     "
	        + "        , UPDATE_ADM_ID = #{updateAdmId }                                 "
	        + "        , UPDATE_DT     = SYSDATE                                                    "
	        + "   WHERE SEQ             = #{tmpSeq}                             "
	        + "     AND '1' = ( SELECT '1'                                                          "
	        + "                   FROM KPC_EL_APPR                                                  "
	        + "                  WHERE SEQ        = #{seq}                      "
	        + "                    AND REQ_EMP_ID = #{reqEmpId})                ";
	@Update(UPDATE_SUBMERCHANT_SERVICE_TMP)
	public int updateSubMerchantServiceTmp(@Param(value="category") String category, @Param(value="name") String name, @Param(value="serviceType") String serviceType,
			@Param(value="useFlag") String useFlag, @Param(value="svcConnId") String svcConnId, @Param(value="svcConnPw") String svcConnPw,
			@Param(value="updateAdmId") String updateAdmId, @Param(value="tmpSeq") String tmpSeq, @Param(value="seq") String seq,
			@Param(value="reqEmpId") String reqEmpId);
	
	public static final String INSERT_SUBMERCHANT_SERVICE_BILLING_TMP = "INSERT INTO SUBMERCHANT_BILLING_TMP( "
			+ " 	SEQ "
			+ " 	,SERVICE_BILLING_ID "
			+ " 	,SERVICE_ID "
			+ " 	,NAME "
			+ " 	,CODE "
			+ " 	,DIVIDER "
			+ " 	,APL_START_DT "
			+ " 	,BANK_NM "
			+ " 	,BANK_ACC_NO "
			+ " 	,BANK_HOLDER "
			+ " 	,BILLING_DT "
			+ " 	,BILLING_DURATION "
			+ " 	,MERCHANT_COMM_TYPE "
			+ " 	,MERCHANT_COMMISION "
			+ " 	,MERCHANT_TAX_TYPE "
			+ " 	,MNG_NM "
			+ " 	,MNG_TEL "
			+ " 	,MNG_EMAIL "
			+ " 	,KPC_MNG_NM "
			+ " 	,KPC_MNG_TEL "
			+ " 	,KPC_MNG_EMAIL "
			+ " 	,DEL_FLAG "
			+ " 	,CREATE_DT "
			+ " 	,CREATE_DESC "
			+ " 	,CREATE_ADM_ID "
			+ " ) VALUES ( "
			+ " 	#{tmpSeq} "
			+ " 	,#{billingId} "
			+ " 	,#{serviceId} "
			+ " 	,#{name} "
			+ " 	,#{code} "
			+ " 	,#{divider} "
			+ " 	,SYSDATE "
			+ " 	,#{bankNm} "
			+ " 	,#{bankAccNo} "
			+ " 	,#{bankHolder} "
			+ " 	,#{billingDt} "
			+ " 	,#{billingDuration} "
			+ " 	,#{merchantCommType} "
			+ " 	,#{merchantCommision} "
			+ " 	,#{merchantTaxType} "
			+ " 	,#{kpcBillingNm} "
			+ " 	,#{kpcBillingTel} "
			+ " 	,#{kpcBillingEmail} "
			+ " 	,#{billingNm} "
			+ " 	,#{billingTel} "
			+ " 	,#{billingEmail} "
			+ " 	,'N' "
			+ " 	,SYSDATE "
			+ " 	,'신규' "
			+ " 	,#{createAdmId} "    
			+ " ) ";
	@Insert(INSERT_SUBMERCHANT_SERVICE_BILLING_TMP)
	public int insertSubMerchantServiceBillingTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="billingId") String serviceBillingId, 
			@Param(value="serviceId") String serviceId, @Param(value="name") String name, @Param(value="code") String code, @Param(value="divider") String divider, 
			@Param(value="bankNm") String bankNm, @Param(value="bankAccNo") String bankAccNo, @Param(value="bankHolder") String bankHolder,
			@Param(value="billingDt") String billingDt, @Param(value="billingDuration") String billingDuration,  
			@Param(value="merchantCommType") String merchantCommType, @Param(value="merchantCommision") String merchantCommision, @Param(value="merchantTaxType") String merchantTaxType, 
			@Param(value="kpcBillingNm") String kpcBillingNm, @Param(value="kpcBillingTel") String kpcBillingTel, @Param(value="kpcBillingEmail") String kpcBillingEmail,
			@Param(value="billingNm") String billingNm, @Param(value="billingTel") String billingTel, @Param(value="billingEmail") String billingEmail,
			@Param(value="createAdmId") String createAdmId);
	
	public static final String UPDATE_SUBMERCHANT_SERVICE_BILLING_TMP = "UPDATE SUBMERCHANT_BILLING_TMP "
	        + "      SET NAME                = #{name}                       "
	        + "         ,CODE                = #{code}                       "
	        + "         ,DIVIDER             = #{divider}                    "
	        + "         ,APL_START_DT        = SYSDATE                                                  "
	        + "         ,BANK_NM             = #{bankNm}                     "
	        + "         ,BANK_ACC_NO         = #{bankAccNo}                  "
	        + "         ,BANK_HOLDER         = #{bankHolder}                 "
	        + "         ,BILLING_DT          = #{billingDt}                  "
	        + "         ,BILLING_DURATION    = #{billingDuration}            "
	        + "         ,MERCHANT_COMM_TYPE  = #{merchantCommType}          "
	        + "         ,MERCHANT_COMMISION  = #{merchantCommision}         "
	        + "         ,MERCHANT_TAX_TYPE   = #{merchantTaxType}           "
	        + "         ,MNG_NM              = #{kpcBillingNm}               "
	        + "         ,MNG_TEL             = #{kpcBillingTel}              "
	        + "         ,MNG_EMAIL           = #{kpcBillingEmail}            "
	        + "         ,KPC_MNG_NM          = #{billingNm}                  "
	        + "         ,KPC_MNG_TEL         = #{billingTel}                 "
	        + "         ,KPC_MNG_EMAIL       = #{billingEmail}               "
	        + "         ,DEL_FLAG            = 'N'                                                      "
	        + "         ,CREATE_DT           = SYSDATE                                                  "
	        + "   WHERE SEQ             = #{tmpSeq}                                 "
	        + "     AND '1' = ( SELECT '1'                                                              "
	        + "                   FROM KPC_EL_APPR                                                      "
	        + "                  WHERE SEQ        = #{seq}                          "
	        + "                    AND REQ_EMP_ID = #{reqEmpId})                    ";
	@Update(UPDATE_SUBMERCHANT_SERVICE_BILLING_TMP)
	public int updateSubMerchantServiceBillingTmp(@Param(value="name") String name, @Param(value="code") String code, @Param(value="divider") String divider,
			@Param(value="bankNm") String bankNm, @Param(value="bankAccNo") String bankAccNo, @Param(value="bankHolder") String bankHolder, 
			@Param(value="billingDt") String billingDt, @Param(value="billingDuration") String billingDuration, 
			@Param(value="merchantCommType") String merchantCommType, @Param(value="merchantCommision") String merchantCommision, @Param(value="merchantTaxType") String merchantTaxType,
			@Param(value="kpcBillingNm") String kpcBillingNm, @Param(value="kpcBillingTel") String kpcBillingTel, @Param(value="kpcBillingEmail") String kpcBillingEmail,
			@Param(value="billingNm") String billingNm, @Param(value="billingTel") String billingTel, @Param(value="billingEmail") String billingEmail,
			@Param(value="tmpSeq") String tmpSeq, @Param(value="seq") String seq, @Param(value="reqEmpId") String reqEmpId);
	
	public static final String GET_MERCHANT_APPROVAL_HISTORY_BY_COUNT = "<script>"
			+ "	SELECT COUNT(1) count "
            + " 	FROM KPC_EL_APPR  A "
            + "     	,MERCHANT_TMP B "
            + "         ,KPC_EMPLOYE  C "
            + "         ,KPC_EMPLOYE  D "
            + "     WHERE A.TMP_SEQ       = B.SEQ "
            + "         AND A.TYPE_CODE  LIKE 'APPR-01%' "
            + "         AND A.REQ_EMP_ID    = C.EMP_ID "
            + "         AND A.APPR_EMP_ID   = D.EMP_ID "
            + "         AND A.CREATE_DT    &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss')"
            + " 	<if test='name != \"\" '> "
	        + " 		AND B.NAME LIKE '%' || #{name} || '%' "
	        + " 	</if> "
	        + " 	<if test='reqEmpNm != \"\" '> "
	        + " 		AND D.NAME LIKE '%' || #{reqEmpNm} || '%' "
	        + " 	</if> "
	        + " 	<if test='historyType != \"\" and historyType == \"APPR-0100\" '> " 
            + " 		AND (A.TYPE_CODE       = 'APPR-0100' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + " 	<if test='historyType != \"\" and historyType != \"APPR-0100\" '> " 
            + " 		AND (A.TYPE_CODE     &lt;&gt; 'APPR-0100' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + "</script>"; 
	@Select(GET_MERCHANT_APPROVAL_HISTORY_BY_COUNT)
	public int getMerchantApprovalHistoryByCount(@Param(value="startDate") String startDate, @Param(value="endDate") String endDate,
			@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, @Param(value="historyType") String historyType);
	public static final String GET_MERCHANT_APPROVAL_HISTORY = "<script>"
			+ " SELECT Z.* "                    
            + "        FROM ( "                      
            + "               SELECT ROWNUM AS RNUM "
            + "                    , X.*           "
            + "                 FROM ( "
            + "                        SELECT A.SEQ "
            + "                             , A.TMP_SEQ "
            + "                             , A.STATUS "
        	+ " 	                            , FNC_ADMIN_CODE_TO_NAME(A.STATUS) STATUS_NM "
            + "                             , A.TYPE_CODE "
            + "                             , FNC_ADMIN_CODE_TO_NAME(A.TYPE_CODE) TYPE_CODE_NM "
            + "                             , A.CREATE_DT "
            + "                             , DECODE(A.STATUS , 'ARST-0001' , '' , TO_CHAR(A.UPDATE_DT,'YYYY-MM-DD')) UPDATE_DT "
            + "                             , B.NAME "
            + "                             , A.REQ_EMP_ID "
            + "                             , C.NAME REQ_EMP_NM "
            + "                             , A.APPR_EMP_ID "
            + "                             , D.NAME APPR_EMP_NM "
            + "                          FROM KPC_EL_APPR  A "
            + "                              ,MERCHANT_TMP B "
            + "                              ,KPC_EMPLOYE  C "
            + "                              ,KPC_EMPLOYE  D "
            + "                         WHERE A.TMP_SEQ      = B.SEQ "
            + "                           AND A.TYPE_CODE  LIKE 'APPR-01%' "
            + "                           AND A.REQ_EMP_ID   = C.EMP_ID "
            + "                           AND A.APPR_EMP_ID  = D.EMP_ID "
            + "                           AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + " 	<if test='name != \"\" '> "
	        + " 		AND B.NAME LIKE '%' || #{name} || '%' "
	        + " 	</if> "
	        + " 	<if test='reqEmpNm != \"\" '> "
	        + " 		AND D.NAME LIKE '%' || #{reqEmpNm} || '%' "
	        + " 	</if> "
	        + " 	<if test='historyType != \"\" and historyType == \"APPR-0100\" '> " 
            + " 		AND (A.TYPE_CODE       = 'APPR-0100' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + " 	<if test='historyType != \"\" and historyType != \"APPR-0100\" '> " 
            + " 		AND (A.TYPE_CODE      &lt;&gt; 'APPR-0100' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "                           
            + "                       ORDER BY A.CREATE_DT DESC "
            + "               ) X                                "                         
            + "             WHERE ROWNUM &lt;= (#{offset} + #{limit}) "             
            + "           ) Z                                     "                               
            + "     WHERE RNUM &gt; #{offset} "
            + "</script>" ;
	@Select(GET_MERCHANT_APPROVAL_HISTORY)
	public List<ApprovalMerchantMerchantApprovalHistory> getMerchantApprovalHistory(@Param(value="startDate") String startDate, @Param(value="endDate") String endDate,
			@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, @Param(value="historyType") String historyType,
			@Param(value="offset") long offset, @Param(value="limit") long limit);
			
//	public static final String GET_MERCHANT_TMP = "SELECT A.SEQ                    "
//            + "             ,A.MERCHANT_ID                                         "
//            + "             ,A.ERP_CODE                                            "
//            + "             ,A.NAME                                                "
//            + "             ,A.NAME_ENG                                            "
//            + "             ,A.ALIAS                                               "
//            + "             ,A.ALIAS_ENG                                           "
//            + "             ,A.USE_FLAG                                            "
//            + "             ,DECODE(A.USE_FLAG ,'Y','사용','미사용') USE_FLAG_NM   "
//            + "             ,A.DEL_FLAG                                            "
//            + "             ,A.CREATE_DT                                           "
//            + "             ,A.CREATE_DESC                                         "
//            + "             ,A.UPDATE_DT                                           "
//            + "             ,A.UPDATE_DESC                                         "
//            + "             ,A.BIZ_KIND                                            "
//            + "             ,A.BIZ_COND                                            "
//            + "             ,A.BIZ_GRP                                             "
//        	+ " 	            ,FNC_ADMIN_CODE_TO_NAME(A.BIZ_GRP) BIZ_GRP_NM      "
//            + "             ,A.CORP_REG_NO                                         "
//            + "             ,A.BIZ_REG_NO                                          "
//            + "             ,A.OPEN_DT                                             "
//            + "             ,A.CLOSE_DT                                            "
//            + "             ,A.CLOSED_FLAG                                         "
//            + "             ,A.CAPITAL_AMT                                         "
//            + "             ,A.EMP_CNT                                             "
//            + "             ,A.STORE_CNT                                           "
//            + "             ,A.AVG_SALE_MONTH                                      "
//            + "             ,A.AVG_SALE_YEAR                                       "
//            + "             ,A.CEO_NM 												"
//            + "             ,A.ZIPCODE                                             "
//            + "             ,A.ADDRESS                                             "
//            + "             ,A.ADDRESS_DTL                                         "
//            + "             ,A.TEL                                                 "
//            + "             ,A.TEL_SUB                                             "
//            + "             ,A.FAX                                                 "
//            + "             ,A.FAX_SUB                                             "
//            + "             ,B.STATUS APPR_STATUS                                  "
//        	+ " 	            ,B.TYPE_CODE APPR_TYPE_CODE                        "
//            + "             ,B.APPR_DESC                                           "
//            + "         FROM MERCHANT_TMP A                                        "
//            + "            , KPC_EL_APPR B                                         "
//            + "        WHERE A.SEQ          = #{tmpSeq}                             "
//            + "          AND A.SEQ          = B.TMP_SEQ                            "
//            + "          AND B.TYPE_CODE LIKE 'APPR-01%'                           "
//            + "          AND (B.APPR_EMP_ID  = #{empId} OR B.REQ_EMP_ID  = #{empId}) ";
//	@Select(GET_MERCHANT_TMP)
//	public ApprovalMerchantMerchantTmp getMerchantTmp(@Param(value="tmpSeq") long tmpSeq, @Param(value="empId") String empId);
	
	
	public static final String GET_SUBMERCHANT_APPROVALS_HISTORY_BY_COUNT = "<script> "
			+ "		SELECT COUNT(1) count                                "
            + "        FROM KPC_EL_APPR  A                                                                                            "
            + "            ,MERCHANT_TMP B                                                                                 "
            + "            ,KPC_EMPLOYE  C                                                                                            "
            + "            ,KPC_EMPLOYE  D                                                                                            "
            + "       WHERE A.TMP_SEQ       = B.SEQ                                                                                   "
            + "         AND A.TYPE_CODE  LIKE 'APPR-02%'                                                                              "
            + "         AND A.REQ_EMP_ID    = C.EMP_ID                                                                                "
            + "         AND A.APPR_EMP_ID   = D.EMP_ID                                                                                "
            + "         AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + " 	<if test='name != \"\" '> "
	        + " 		AND B.NAME = '%' || #{name} || '%' "
	        + " 	</if> "
	        + " 	<if test='reqEmpNm != \"\" '> "
	        + " 		AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 	</if> "
	        + " 	<if test='historyType != \"\" and historyType == \"APPR-0300\" '> " 
            + " 		AND (A.TYPE_CODE       = 'APPR-0200' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + " 	<if test='historyType != \"\" and historyType != \"APPR-0300\" '> " 
            + " 		AND (A.TYPE_CODE      &lt;&gt; 'APPR-0200' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + "</script>";
	@Select(GET_SUBMERCHANT_APPROVALS_HISTORY_BY_COUNT)
	public int getSubMerchantApprovalsByCount(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate);
	
	public static final String GET_SUBMERCHANT_APPROVALS_HISTORY = "<script> "
			+ " 	SELECT Z.*                                                                                                                        "
            + "        FROM (                                                                                                                        "
            + "               SELECT ROWNUM AS RNUM                                                                                                  "
            + "                    , X.*                                                                                                             "
            + "                 FROM (                                                                                                               "
            + "                        SELECT A.SEQ                                                                                                  "
            + "                             , A.TMP_SEQ                                                                                              "
            + "                             , A.STATUS                                                                                               "
        	+ " 	                            , FNC_ADMIN_CODE_TO_NAME(A.STATUS) STATUS_NM                                                         "
            + "                             , A.TYPE_CODE                                                                                            "
            + "                             , FNC_ADMIN_CODE_TO_NAME(A.TYPE_CODE) TYPE_CODE_NM                                                       "
            + "                             , A.CREATE_DT                                                                                            "
            + "                             , DECODE(A.STATUS , 'ARST-0001' , '' , TO_CHAR(A.UPDATE_DT,'YYYY-MM-DD')) UPDATE_DT                      "
            + "                             , B.NAME                                                                                                 "
            + "                             , A.REQ_EMP_ID                                                                                           "
            + "                             , C.NAME REQ_EMP_NM                                                                                      "
            + "                             , A.APPR_EMP_ID                                                                                          "
            + "                             , D.NAME APPR_EMP_NM                                                                                     "
            + "                          FROM KPC_EL_APPR  A                                                                                         "
            + "                              ,MERCHANT_TMP B                                                                              "
            + "                              ,KPC_EMPLOYE  C                                                                                         "
            + "                              ,KPC_EMPLOYE  D                                                                                         "
            + "                         WHERE A.TMP_SEQ      = B.SEQ                                                                                 "
            + "                           AND A.TYPE_CODE  LIKE 'APPR-02%'                                                                           "
            + "                           AND A.REQ_EMP_ID   = C.EMP_ID                                                                              "
            + "                           AND A.APPR_EMP_ID  = D.EMP_ID                                                                              "
            + "                           AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + "					 	<if test='name != \"\" '> "
	        + " 						  AND B.NAME = '%' || #{name} || '%' "
	        + " 					</if> "
	        + " 					<if test='reqEmpNm != \"\" '> "
	        + " 						  AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 					</if> "
	        + " 					<if test='historyType != \"\" and historyType == \"APPR-0200\" '> " 
            + " 						  AND (A.TYPE_CODE       = 'APPR-0200' AND A.STATUS  = 'ARST-0001') " 
            + " 					</if> "
            + " 					<if test='historyType != \"\" and historyType != \"APPR-0200\" '> " 
            + " 						  AND (A.TYPE_CODE     &lt;&gt; 'APPR-0200' AND A.STATUS  = 'ARST-0001') "
            + "						</if>                                "
            + "				ORDER BY A.CREATE_DT DESC                    "
            + "               ) X                                        "                
            + "             WHERE ROWNUM &lt;= (#{offset} + #{limit})         "    
            + "           ) Z                                            "                       
            + "     WHERE RNUM &gt; #{offset} "
            + "</script>";
	@Select(GET_SUBMERCHANT_APPROVALS_HISTORY)
	public List<ApprovalMerchantMerchantApprovalHistory> getSubMerchantApprovals(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate,
			@Param(value="offset") long offset, @Param(value="limit") long limit);
	
	public static final String GET_SUBMERCHANT_SERVICE_APPROVALS_HISTORY_BY_COUNT = "<script> "
			+ "		SELECT COUNT(1) count                                "
            + "        FROM KPC_EL_APPR  A                                                                                            "
            + "            ,SUBMERCHANT_SERVICE_TMP B                                                                                 "
            + "            ,KPC_EMPLOYE  C                                                                                            "
            + "            ,KPC_EMPLOYE  D                                                                                            "
            + "       WHERE A.TMP_SEQ       = B.SEQ                                                                                   "
            + "         AND A.TYPE_CODE  LIKE 'APPR-03%'                                                                              "
            + "         AND A.REQ_EMP_ID    = C.EMP_ID                                                                                "
            + "         AND A.APPR_EMP_ID   = D.EMP_ID                                                                                "
            + "         AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + " 	<if test='name != \"\" '> "
	        + " 		AND B.NAME = '%' || #{name} || '%' "
	        + " 	</if> "
	        + " 	<if test='reqEmpNm != \"\" '> "
	        + " 		AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 	</if> "
	        + " 	<if test='historyType != \"\" and historyType == \"APPR-0200\" '> " 
            + " 		AND (A.TYPE_CODE       = 'APPR-0200' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + " 	<if test='historyType != \"\" and historyType != \"APPR-0200\" '> " 
            + " 		AND (A.TYPE_CODE      &lt;&gt; 'APPR-0200' AND A.STATUS  = 'ARST-0001') "
            + " 	</if> "
            + "</script>";
	@Select(GET_SUBMERCHANT_SERVICE_APPROVALS_HISTORY_BY_COUNT)
	public int getSubMerchantServiceApprovalsByCount(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate);
	
	public static final String GET_SUBMERCHANT_SERVICE_APPROVALS_HISTORY = "<script> "
			+ " 	SELECT Z.*                                                                                                                        "
            + "        FROM (                                                                                                                        "
            + "               SELECT ROWNUM AS RNUM                                                                                                  "
            + "                    , X.*                                                                                                             "
            + "                 FROM (                                                                                                               "
            + "                        SELECT A.SEQ                                                                                                  "
            + "                             , A.TMP_SEQ                                                                                              "
            + "                             , A.STATUS                                                                                               "
        	+ " 	                            , FNC_ADMIN_CODE_TO_NAME(A.STATUS) STATUS_NM                                                         "
            + "                             , A.TYPE_CODE                                                                                            "
            + "                             , FNC_ADMIN_CODE_TO_NAME(A.TYPE_CODE) TYPE_CODE_NM                                                       "
            + "                             , A.CREATE_DT                                                                                            "
            + "                             , DECODE(A.STATUS , 'ARST-0001' , '' , TO_CHAR(A.UPDATE_DT,'YYYY-MM-DD')) UPDATE_DT                      "
            + "                             , B.NAME                                                                                                 "
            + "                             , A.REQ_EMP_ID                                                                                           "
            + "                             , C.NAME REQ_EMP_NM                                                                                      "
            + "                             , A.APPR_EMP_ID                                                                                          "
            + "                             , D.NAME APPR_EMP_NM                                                                                     "
            + "                          FROM KPC_EL_APPR  A                                                                                         "
            + "                              ,SUBMERCHANT_SERVICE_TMP B                                                                              "
            + "                              ,KPC_EMPLOYE  C                                                                                         "
            + "                              ,KPC_EMPLOYE  D                                                                                         "
            + "                         WHERE A.TMP_SEQ      = B.SEQ                                                                                 "
            + "                           AND A.TYPE_CODE  LIKE 'APPR-03%'                                                                           "
            + "                           AND A.REQ_EMP_ID   = C.EMP_ID                                                                              "
            + "                           AND A.APPR_EMP_ID  = D.EMP_ID                                                                              "
            + "                           AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + "					 	<if test='name != \"\" '> "
	        + " 						  AND B.NAME = '%' || #{name} || '%' "
	        + " 					</if> "
	        + " 					<if test='reqEmpNm != \"\" '> "
	        + " 						  AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 					</if> "
	        + " 					<if test='historyType != \"\" and historyType == \"APPR-0300\" '> " 
            + " 						  AND (A.TYPE_CODE       = 'APPR-0300' AND A.STATUS  = 'ARST-0001') " 
            + " 					</if> "
            + " 					<if test='historyType != \"\" and historyType != \"APPR-0300\" '> " 
            + " 						  AND (A.TYPE_CODE     &lt;&gt; 'APPR-0300' AND A.STATUS  = 'ARST-0001') "
            + "						</if>                                "
            + "				ORDER BY A.CREATE_DT DESC                    "
            + "               ) X                                        "                
            + "             WHERE ROWNUM &lt;= (#{offset} + #{limit})         "    
            + "           ) Z                                            "                       
            + "     WHERE RNUM &gt; #{offset} "
            + "</script>";
	@Select(GET_SUBMERCHANT_SERVICE_APPROVALS_HISTORY)
	public List<ApprovalMerchantMerchantApprovalHistory> getSubMerchantServiceApprovals(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate,
			@Param(value="offset") long offset, @Param(value="limit") long limit);
	
	public static final String GET_SUBMERCHANT_SERVICE_BILLING_APPROVALS_HISTORY_BY_COUNT = "<script> "
			+ "		SELECT COUNT(1) count                                "
            + "        FROM KPC_EL_APPR  A                                                                                            "
            + "            ,SUBMERCHANT_BILLING_TMP B                                                                                 "
            + "            ,KPC_EMPLOYE  C                                                                                            "
            + "            ,KPC_EMPLOYE  D                                                                                            "
            + "       WHERE A.TMP_SEQ       = B.SEQ                                                                                   "
            + "         AND A.TYPE_CODE  LIKE 'APPR-04%'                                                                              "
            + "         AND A.REQ_EMP_ID    = C.EMP_ID                                                                                "
            + "         AND A.APPR_EMP_ID   = D.EMP_ID                                                                                "
            + "         AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + " 	<if test='name != \"\" '> "
	        + " 		AND B.NAME = '%' || #{name} || '%' "
	        + " 	</if> "
	        + " 	<if test='reqEmpNm != \"\" '> "
	        + " 		AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 	</if> "
	        + " 	<if test='historyType != \"\" and historyType == \"APPR-0400\" '> " 
            + " 		AND (A.TYPE_CODE       = 'APPR-0400' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + " 	<if test='historyType != \"\" and historyType != \"APPR-0300\" '> " 
            + " 		AND (A.TYPE_CODE      &lt;&gt; 'APPR-0400' AND A.STATUS  = 'ARST-0001') " 
            + " 	</if> "
            + "</script>";
	@Select(GET_SUBMERCHANT_SERVICE_BILLING_APPROVALS_HISTORY_BY_COUNT)
	public int getSubMerchantServiceBillingApprovalsByCount(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate);
	
	public static final String GET_SUBMERCHANT_SERVICE_BILLING_APPROVALS_HISTORY = "<script> "
			+ " 	SELECT Z.*                                                                                                                        "
            + "        FROM (                                                                                                                        "
            + "               SELECT ROWNUM AS RNUM                                                                                                  "
            + "                    , X.*                                                                                                             "
            + "                 FROM (                                                                                                               "
            + "                        SELECT A.SEQ                                                                                                  "
            + "                             , A.TMP_SEQ                                                                                              "
            + "                             , A.STATUS                                                                                               "
        	+ " 	                            , FNC_ADMIN_CODE_TO_NAME(A.STATUS) STATUS_NM                                                         "
            + "                             , A.TYPE_CODE                                                                                            "
            + "                             , FNC_ADMIN_CODE_TO_NAME(A.TYPE_CODE) TYPE_CODE_NM                                                       "
            + "                             , A.CREATE_DT                                                                                            "
            + "                             , DECODE(A.STATUS , 'ARST-0001' , '' , TO_CHAR(A.UPDATE_DT,'YYYY-MM-DD')) UPDATE_DT                      "
            + "                             , B.NAME                                                                                                 "
            + "                             , A.REQ_EMP_ID                                                                                           "
            + "                             , C.NAME REQ_EMP_NM                                                                                      "
            + "                             , A.APPR_EMP_ID                                                                                          "
            + "                             , D.NAME APPR_EMP_NM                                                                                     "
            + "                          FROM KPC_EL_APPR  A                                                                                         "
            + "                              ,SUBMERCHANT_BILLING_TMP B                                                                              "
            + "                              ,KPC_EMPLOYE  C                                                                                         "
            + "                              ,KPC_EMPLOYE  D                                                                                         "
            + "                         WHERE A.TMP_SEQ      = B.SEQ                                                                                 "
            + "                           AND A.TYPE_CODE  LIKE 'APPR-02%'                                                                           "
            + "                           AND A.REQ_EMP_ID   = C.EMP_ID                                                                              "
            + "                           AND A.APPR_EMP_ID  = D.EMP_ID                                                                              "
            + "                           AND A.CREATE_DT &gt;= #{startDate} AND A.CREATE_DT &lt;= TO_DATE(#{endDate} || '235959' , 'YYYY-MM-DD hh24:mi:ss') "
            + "					 	<if test='name != \"\" '> "
	        + " 						  AND B.NAME = '%' || #{name} || '%' "
	        + " 					</if> "
	        + " 					<if test='reqEmpNm != \"\" '> "
	        + " 						  AND D.NAME = '%' || #{reqEmpNm} || '%' "
	        + " 					</if> "
	        + " 					<if test='historyType != \"\" and historyType == \"APPR-0400\" '> " 
            + " 						  AND (A.TYPE_CODE       = 'APPR-0400' AND A.STATUS  = 'ARST-0001') " 
            + " 					</if> "
            + " 					<if test='historyType != \"\" and historyType != \"APPR-0300\" '> " 
            + " 						  AND (A.TYPE_CODE      &lt;&gt; 'APPR-0400' AND A.STATUS  = 'ARST-0001') "
            + "						</if>                                "
            + "				ORDER BY A.CREATE_DT DESC                    "
            + "               ) X                                        "                
            + "             WHERE ROWNUM &lt;= (#{offset} + #{limit})       "    
            + "           ) Z                                            "                       
            + "     WHERE RNUM &gt; #{offset} "
            + "</script>";
	@Select(GET_SUBMERCHANT_SERVICE_BILLING_APPROVALS_HISTORY)
	public List<ApprovalMerchantMerchantApprovalHistory> getSubMerchantServiceBillingApprovals(@Param(value="name") String name, @Param(value="reqEmpNm") String reqEmpNm, 
			@Param(value="typeCode") String typeCode, @Param(value="historyType") String historyType, @Param(value="empId") String empId, 
			@Param(value="startDate") String startDate, @Param(value="endDate") String endDate,
			@Param(value="offset") long offset, @Param(value="limit") long limit);
	
	public static final String GET_SUBMERCHANT_TMP = "SELECT A.SEQ									"
            + "             ,A.SUBMERCHANT_ID                                                           "
            + "             ,A.ERP_CODE                                                                 "
            + "             ,A.DEPTH                                                                    "
            + "             ,A.PARENT_ID                                                                "
            + "             ,(SELECT NAME FROM MERCHANT WHERE MERCHANT_ID = A.PARENT_ID) PARENT_NM      "
            + "             ,A.CHILD_ID                                                                 "
            + "             ,A.NAME                                                                     "
            + "             ,A.NAME_ENG                                                                 "
            + "             ,A.ALIAS                                                                    "
            + "             ,A.ALIAS_ENG                                                                "
            + "             ,A.USE_FLAG                                                                 "
            + "             ,DECODE(A.use_flag ,'Y','사용','미사용') USE_FLAG_NAME                      "
            + "             ,A.REUSE_FLAG                                                               "
            + "             ,A.DEL_FLAG                                                                 "
            + "             ,A.PG_ID                                                                    "
            + "             ,A.PG_PW                                                                    "
            + "             ,A.AGENT_ID                                                                 "
            + "             ,A.AGENT_PW                                                                 "
            + "             ,A.CREATE_DT                                                                "
            + "             ,A.CREATE_DESC                                                              "
            + "             ,A.UPDATE_DT                                                                "
            + "             ,A.UPDATE_DESC                                                              "
            + "             ,A.BIZ_KIND                                                                 "
            + "             ,A.BIZ_COND                                                                 "
            + "             ,A.CORP_REG_NO                                                              "
            + "             ,A.BIZ_REG_NO                                                               "
            + "             ,A.CUST_NM                                                                  "
            + "             ,A.CUST_TEL                                                                 "
            + "             ,A.CEO_NM                                                                   "
            + "             ,A.TYPE                                                                     "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.TYPE) TYPE_NM                                     "
            + "             ,A.OPEN_DT                                                                  "
            + "             ,A.BANK_NM                                                                  "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.BANK_NM) BANK_CD_NM                               "
            + "             ,A.BANK_ACC_NO                                                              "
            + "             ,A.BANK_HOLDER                                                              "
            + "             ,A.ZIPCODE                                                                  "
            + "             ,A.ADDRESS                                                                  "
            + "             ,A.ADDRESS_DTL                                                              "
            + "             ,A.TEL                                                                      "
            + "             ,A.FAX                                                                      "
            + "             ,A.TAX_CUST_NM                                                              "
            + "             ,A.TAX_EMAIL                                                                "
            + "             ,A.TAX_TEL                                                                  "
            + "             ,A.TAX_PHONE                                                                "
            + "             ,A.TAX_FAX                                                                  "
            + "             ,A.SALES_NM                                                                 "
            + "             ,A.SALES_TEL                                                                "
            + "             ,A.BILLING_NM                                                               "
            + "             ,A.BILLING_TEL                                                              "
            + "             ,A.KPC_SALES_NM                                                             "
            + "             ,A.KPC_SALES_TEL                                                            "
            + "             ,A.KPC_BILLING_NM                                                           "
            + "             ,A.KPC_BILLING_TEL                                                          "
            + "             ,A.URL01                                                                    "
            + "             ,A.URL02                                                                    "
            + "             ,A.URL_HOME                                                                 "
            + "             ,B.STATUS APPR_STATUS                                                       "
        	+ " 	            ,B.TYPE_CODE APPR_TYPE_CODE                                             "
            + "             ,B.APPR_DESC                                                                "
            + "         FROM SUBMERCHANT_TMP A                                                          "
            + "            , KPC_EL_APPR B                                                              "
            + "        WHERE A.SEQ          = #{tmpSeq}                                                  "
            + "          AND A.SEQ          = B.TMP_SEQ                                                 "
            + "          AND B.TYPE_CODE LIKE 'APPR-02%'                                                "
            + "          AND (B.APPR_EMP_ID  = #{empId} OR B.REQ_EMP_ID  = #{empId}) ";
	@Select(GET_SUBMERCHANT_TMP)
	public ApprovalMerchantSubMerchantTmp getSubMerchantTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="empId") String empId);
	
	public static final String GET_SUBMERCHANT_SERVICE_TMP = "SELECT A.SEQ      "
            + "             ,A.SERVICE_ID                                           "
            + "             ,A.SUBMERCHANT_ID                                       "
            + "             ,A.NAME                                                 "
            + "             ,A.CATEGORY                                             "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.CATEGORY) CATEGORY_NM         "
            + "             ,A.TYPE TYPE                                            "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.TYPE) TYPE_NM                 "
            + "             ,A.USE_FLAG                                             "
            + "             ,DECODE(A.USE_FLAG ,'Y','사용','미사용') USE_FLAG_NM    "
            + "             ,A.DEL_FLAG                                             "
            + "             ,A.SVC_AUTH_TYPE                                        "
            + "             ,A.SVC_CONN_ID                                          "
            + "             ,A.SVC_CONN_PW                                          "
            + "             ,A.SALE_CATEGORY                                        "
            + "             ,A.SALE_DIVIDER                                         "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.SALE_DIVIDER) SALE_DIVIDER_NM "
            + "             ,A.CREATE_DT                                            "
            + "             ,A.CREATE_DESC                                          "
            + "             ,A.CREATE_ADM_ID                                        "
            + "             ,A.UPDATE_DT                                            "
            + "             ,A.UPDATE_DESC                                          "
            + "             ,A.UPDATE_ADM_ID                                        "
            + "             ,A.SVC_ALIAS                                            "
            + "             ,A.FRC_FLAG                                             "
            + "             ,A.FRC_DESC                                             "
            + "             ,B.STATUS APPR_STATUS                                   "
        	+ " 	            ,B.TYPE_CODE APPR_TYPE_CODE                         "
            + "             ,B.APPR_DESC                                            "
            + "         FROM SUBMERCHANT_SERVICE_TMP A                              "
            + "            , KPC_EL_APPR B                                          "
            + "        WHERE A.SEQ          = #{tmpSeq}                              "
            + "          AND A.SEQ          = B.TMP_SEQ                             "
            + "          AND B.TYPE_CODE LIKE 'APPR-03%'                            "
            + "          AND (B.APPR_EMP_ID  = #{empId} OR B.REQ_EMP_ID  = #{empId})  ";
	@Select(GET_SUBMERCHANT_SERVICE_TMP)
	public ApprovalMerchantSubMerchantServiceTmp getSubMerchantServiceTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="empId") String empId);
	
	public static final String GET_SUBMERHCNAT_SERVICE_BILLING_TMP = "SELECT A.SERVICE_BILLING_ID                   "     
            + "             ,A.SERVICE_ID                                                                               "
            + "             ,A.NAME                                                                                     "
            + "             ,A.CODE                                                                                     "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.CODE) CODENAME                                                    "
            + "             ,A.DIVIDER                                                                                  "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.DIVIDER) DIVIDERNAME                                              "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.BANK_NM) BANKNM                                                   "
            + "             ,A.BANK_NM                         BANKCD                                                   "
            + "             ,A.BANK_ACC_NO                                                                              "
            + "             ,A.VR_BANK_NM                                                                               "
            + "             ,A.VR_BANK_ACC_NO                                                                           "
            + "             ,A.BANK_HOLDER                                                                              "
            + "             ,A.BILLING_DT                                                                               "
            + "             ,A.BILLING_DURATION                                                                         "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.BILLING_DURATION) BILLINGDURATIONNAME                             "
            + "             ,A.MERCHANT_COMM_TYPE                                                                       "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.MERCHANT_COMM_TYPE) MERCHANTCOMMTYPENAME                          "
            + "             ,NVL(RTRIM(TO_CHAR(A.MERCHANT_COMMISION,'FM9999999999990.99'),'.'),0) MERCHANT_COMMISION    "                   
            + "             ,A.MERCHANT_TAX_TYPE                                                                        "
            + "             ,FNC_ADMIN_CODE_TO_NAME(A.MERCHANT_TAX_TYPE) MERCHANTTAXTYPENAME                            "
            + "             ,A.MERCHANT_TAX                                                                             "
            + "             ,A.MNG_NM                                                                                   "
            + "             ,A.MNG_TEL                                                                                  "
            + "             ,A.MNG_EMAIL                                                                                "
            + "             ,A.KPC_MNG_NM                                                                               "
            + "             ,A.KPC_MNG_TEL                                                                              "
            + "             ,A.KPC_MNG_EMAIL                                                                            "
            + "             ,A.CREATE_DT                                                                                "
        	+ " 	            ,A.APL_END_DT                                                                           "
            + "             ,B.STATUS APPR_STATUS                                                                       "
        	+ " 	            ,B.TYPE_CODE APPR_TYPE_CODE                                                             "
            + "             ,B.APPR_DESC                                                                                "
            + "         FROM SUBMERCHANT_BILLING_TMP A                                                                  "
            + "            , KPC_EL_APPR B                                                                              "
            + "        WHERE A.SEQ          = #{tmpSeq}                                                                  "
            + "          AND A.SEQ          = B.TMP_SEQ                                                                 "
            + "          AND B.TYPE_CODE LIKE 'APPR-04%'                                                                "
            + "          AND (B.APPR_EMP_ID  = #{empId} OR B.REQ_EMP_ID  = #{empId})                                      ";
	@Select(GET_SUBMERHCNAT_SERVICE_BILLING_TMP)
	public ApprovalMerchantSubMerchantBillingTmp getSubMerchantServiceBillingTmp(@Param(value="tmpSeq") String tmpSeq, @Param(value="empId") String empId);
	
}
