package kr.co.kpcard.billingservice.app.repository.settlement.gs;

import java.util.List;

import javax.annotation.Resource;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface GsSettlementMapper {
	
	public static final String GS_SM_SELECT_SQL =""
							        +"<script>"
									+" SELECT  SALESDATE saleDt"
									+"        ,BRANCHCODE storeCd"
									+"        ,ORDERNO dealNo"
									+"        ,APLNO approvalNo"
									+"        ,APLDATE approvalDt"
									+"        ,APLTIME approvalTime"
									+"        ,GIFT_NO"
									+"        ,GIFT_CHECK"
									+"        ,(SELECT EXTEND_NO"
									+"            FROM GIFTEXTEND"
									+"           WHERE GIFT_NO = A.GIFT_NO) AS cardNo"
									+"        ,ORDERAMT dealAmt"
									+"        ,TTYPE dealType"
									+"        ,ATYPE dealDivider"
									+"        ,PTYPE payType"
									+"  FROM   (SELECT SALESDATE,"
									+"                 DECODE(BRANCHCODE,MERCHANTID,'',BRANCHCODE) BRANCHCODE,"
									+"                 ORDERNO,"
									+"                 APLNO,"
									+"                 APLDATE,"
									+"                 APLTIME,"
									+"                 (SELECT MAX(B.GIFT_NO)"
									+"                  FROM   ORDERDETAIL A,"
									+"                         (SELECT GIFT_NO,"
									+"                                 SEQ_NO"
									+"                          FROM   GIFTCREATE"
									+"                          UNION ALL"
									+"                          SELECT GIFT_NO,"
									+"                                 SEQ_NO"
									+"                          FROM   GIFTDELETE) B"
									+"                  WHERE  A.C_SERIAL = B.SEQ_NO"
									+"                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
									+"                 (SELECT MAX(B.GIFT_CHECK)"
									+"                  FROM   ORDERDETAIL A,"
									+"                         (SELECT GIFT_CHECK,"
									+"                                 SEQ_NO"
									+"                          FROM   GIFTCREATE"
									+"                          UNION ALL"
									+"                          SELECT GIFT_CHECK,"
									+"                                 SEQ_NO"
									+"                          FROM   GIFTDELETE) B"
									+"                  WHERE  A.C_SERIAL = B.SEQ_NO"
									+"                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
									+"                 ORDERAMT,"
									+"                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
									+"                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
									+"                 '0' PTYPE"
									+"          FROM   ORDERLIST_POS"
									+"          WHERE  MERCHANTID = #{pgOnline}"
									+ "			AND    MERCHANTID != BRANCHCODE"
									+"          AND    SALESDATE =  TO_CHAR(TO_DATE(#{workDt}) - 1 , 'YYYYMMDD')"
									+"          UNION ALL"
									+"          SELECT SALESDATE,"
									+"                 BRANCHCODE,"
									+"                 APLORDERNO ORDERNO,"
									+"                 APLNO,"
									+"                 APLDATE,"
									+"                 APLTIME,"
									+"                 (SELECT MAX(TICKET_SNO)"
									+"                  FROM   ACTIVE_APL_DETAIL"
									+"                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
									+"                 (SELECT MAX(B.GIFT_CHECK)"
									+"                  FROM   ACTIVE_APL_DETAIL A,"
									+"                         (SELECT GIFT_CHECK,"
									+"                                 GIFT_NO"
									+"                          FROM   GIFTCREATE"
									+"                          UNION ALL"
									+"                          SELECT GIFT_CHECK,"
									+"                                 GIFT_NO"
									+"                          FROM   GIFTDELETE) B"
									+"                  WHERE  A.TICKET_SNO = B.GIFT_NO"
									+"                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
									+"                 (SELECT CREATE_AMT"
									+"                  FROM   (SELECT GIFT_NO,"
									+"                                 CREATE_AMT"
									+"                          FROM   GIFTDELETE ) A"
									+"                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
									+"                          FROM   ACTIVE_APL_DETAIL A"
									+"                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
									+"                  UNION ALL"
									+"                  SELECT CREATE_AMT"
									+"                  FROM   (SELECT GIFT_NO,"
									+"                                 CREATE_AMT"
									+"                          FROM   GIFTCREATE ) A"
									+"                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
									+"                          FROM   ACTIVE_APL_DETAIL A"
									+"                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
									+"                 'ACT' TTYPE,"
									+"                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
									+"                 NVL(PAY_METHDO, '0') PTYPE"
									+"          FROM   ACTIVE_APPROVAL"
									+"          WHERE  APLONLINEID = #{otisOnline}"
									+"          AND    SALESDATE =  TO_CHAR(TO_DATE(#{workDt}) - 1 , 'YYYYMMDD')"
									+"          UNION ALL"
									+"          SELECT SALESDATE,"
									+"                 BRANCHCODE,"
									+"                 APLORDERNO ORDERNO,"
									+"                 APLNO,"
									+"                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
									+"                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
									+"                 GIFT_NO,"
									+"                 (SELECT GIFT_CHECK"
									+"                  FROM   (SELECT GIFT_CHECK,"
									+"                                 GIFT_NO"
									+"                          FROM   GIFTCREATE"
									+"                          UNION ALL"
									+"                          SELECT GIFT_CHECK,"
									+"                                 GIFT_NO"
									+"                          FROM   GIFTDELETE)"
									+"                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
									+"                 RC_AMT ORDERAMT,"
									+"                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TS1', 'TRN') TTYPE,"
									+"                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TS1', '0') ATYPE,"
									+"                 NVL(PAY_METHDO, '0') PTYPE"
									+"          FROM   RC_APPROVAL"
									+"          WHERE  APLONLINEID = #{otisOnline}"
									+ "			AND    BRANCHCODE IS NOT NULL"									
									+"          AND    SALESDATE =  TO_CHAR(TO_DATE(#{workDt}) - 1 , 'YYYYMMDD')"
									+"          AND    APLSTATUS IN ('O1','D1','TS1') ) A"
									+"  ORDER BY TTYPE, ATYPE, APLNO"
							        +"</script>";

	public static final String GS_POP_SELECT_SQL =""
        +"<script>"
		+" SELECT  SALESDATE saleDt"
		+"        ,BRANCHCODE storeCd"
		+"        ,ORDERNO dealNo"
		+"        ,APLNO approvalNo"
		+"        ,APLDATE approvalDt"
		+"        ,APLTIME approvalTime"
		+"        ,GIFT_NO"
		+"        ,GIFT_CHECK"
		+"        ,(SELECT EXTEND_NO"
		+"            FROM GIFTEXTEND"
		+"           WHERE GIFT_NO = A.GIFT_NO) AS cardNo"
		+"        ,ORDERAMT dealAmt"
		+"        ,TTYPE dealType"
		+"        ,ATYPE dealDivider"
		+"        ,PTYPE payType"
		+"  FROM   (SELECT SALESDATE,"
		+"                 BRANCHCODE,"
		+"                 ORDERNO,"
		+"                 APLNO,"
		+"                 APLDATE,"
		+"                 APLTIME,"
		+"                 (SELECT MAX(B.GIFT_NO)"
		+"                  FROM   ORDERDETAIL A,"
		+"                         (SELECT GIFT_NO,"
		+"                                 SEQ_NO"
		+"                          FROM   GIFTCREATE"
		+"                          UNION ALL"
		+"                          SELECT GIFT_NO,"
		+"                                 SEQ_NO"
		+"                          FROM   GIFTDELETE) B"
		+"                  WHERE  A.C_SERIAL = B.SEQ_NO"
		+"                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
		+"                 (SELECT MAX(B.GIFT_CHECK)"
		+"                  FROM   ORDERDETAIL A,"
		+"                         (SELECT GIFT_CHECK,"
		+"                                 SEQ_NO"
		+"                          FROM   GIFTCREATE"
		+"                          UNION ALL"
		+"                          SELECT GIFT_CHECK,"
		+"                                 SEQ_NO"
		+"                          FROM   GIFTDELETE) B"
		+"                  WHERE  A.C_SERIAL = B.SEQ_NO"
		+"                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
		+"                 ORDERAMT,"
		+"                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
		+"                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
		+"                 '0' PTYPE"
		+"          FROM   ORDERLIST_POS"
		+"          WHERE  MERCHANTID = #{pgOnline}"
		+ "			AND    MERCHANTID != BRANCHCODE"
		+"          AND    ORDERDATE =  TO_CHAR(TO_DATE(#{workDt}) - 1 , 'YYYYMMDD')"
		+"          UNION ALL"
		+"          SELECT SALESDATE,"
		+"                 BRANCHCODE,"
		+"                 APLORDERNO ORDERNO,"
		+"                 APLNO,"
		+"                 APLDATE,"
		+"                 APLTIME,"
		+"                 (SELECT MAX(TICKET_SNO)"
		+"                  FROM   ACTIVE_APL_DETAIL"
		+"                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
		+"                 (SELECT MAX(B.GIFT_CHECK)"
		+"                  FROM   ACTIVE_APL_DETAIL A,"
		+"                         (SELECT GIFT_CHECK,"
		+"                                 GIFT_NO"
		+"                          FROM   GIFTCREATE"
		+"                          UNION ALL"
		+"                          SELECT GIFT_CHECK,"
		+"                                 GIFT_NO"
		+"                          FROM   GIFTDELETE) B"
		+"                  WHERE  A.TICKET_SNO = B.GIFT_NO"
		+"                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
		+"                 (SELECT CREATE_AMT"
		+"                  FROM   (SELECT GIFT_NO,"
		+"                                 CREATE_AMT"
		+"                          FROM   GIFTDELETE ) A"
		+"                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		+"                          FROM   ACTIVE_APL_DETAIL A"
		+"                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
		+"                  UNION ALL"
		+"                  SELECT CREATE_AMT"
		+"                  FROM   (SELECT GIFT_NO,"
		+"                                 CREATE_AMT"
		+"                          FROM   GIFTCREATE ) A"
		+"                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		+"                          FROM   ACTIVE_APL_DETAIL A"
		+"                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
		+"                 'ACT' TTYPE,"
		+"                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
		+"                 NVL(PAY_METHDO, '0') PTYPE"
		+"          FROM   ACTIVE_APPROVAL"
		+"          WHERE  APLONLINEID = #{otisOnline}"
		+"          AND    APLDATE =  TO_CHAR(TO_DATE(#{workDt}) - 1 , 'YYYYMMDD')"
		+"          UNION ALL"
		+"          SELECT SALESDATE,"
		+"                 BRANCHCODE,"
		+"                 APLORDERNO ORDERNO,"
		+"                 APLNO,"
		+"                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
		+"                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
		+"                 GIFT_NO,"
		+"                 (SELECT GIFT_CHECK"
		+"                  FROM   (SELECT GIFT_CHECK,"
		+"                                 GIFT_NO"
		+"                          FROM   GIFTCREATE"
		+"                          UNION ALL"
		+"                          SELECT GIFT_CHECK,"
		+"                                 GIFT_NO"
		+"                          FROM   GIFTDELETE)"
		+"                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
		+"                 RC_AMT ORDERAMT,"
		+"                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TS1', 'TRN') TTYPE,"
		+"                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TS1', '0') ATYPE,"
		+"                 NVL(PAY_METHDO, '0') PTYPE"
		+"          FROM   RC_APPROVAL"
		+"          WHERE  APLONLINEID = #{otisOnline}"
		+ "			AND    BRANCHCODE IS NOT NULL"	
		+"          AND    APLDATE BETWEEN TO_DATE(#{workDt} || '000000' , 'YYYYMMDDHH24MISS') - 1  and TO_DATE(#{workDt} || '235959' , 'YYYYMMDDHH24MISS') - 1 "
		+"          AND    APLSTATUS IN ('O1','D1','TS1') ) A"
		+"  ORDER BY TTYPE, ATYPE, APLNO"
        +"</script>";


	public static final String INSERT_SQL =""
			+"<script>"
			+"INSERT ALL"
			+" <foreach collection='gsSettlementDataList' item='data' index='index' separator='' close=''>"
			+"  INTO SETTLE_GS"
			+"  VALUES ("
			+"		   #{data.workDt      }" 
			+"		  ,#{jobDivider       }" 
			//+"		  ,(SELECT (NVL(MAX(TO_NUMBER(SEQ)), 0) + 1) + #{index} FROM SETTLE_GS WHERE WORK_DT = #{data.workDt} AND JOB_DIVIDER = #{jobDivider})"
			+"		  ,(#{index			  } + 1) + #{startIdx} "		
			+"		  ,#{data.saleDt      }" 
			+"		  ,#{data.storeCd     }" 
			+"		  ,#{data.dealNo      }" 
			+"		  ,#{data.approvalNo  }" 
			+"		  ,#{data.approvalDt  }" 
			+"		  ,#{data.approvalTime}" 
			+"		  ,#{data.cardNo      }" 
			+"		  ,#{data.dealAmt     }" 
			+"		  ,#{data.orderAmt    }" 
			+"		  ,#{data.dealType    }" 
			+"		  ,#{data.dealDivider }" 
			+"		  ,#{data.creditCorp  }" 
			+"		  ,#{data.creditAplNo }" 
			+"		  ,#{data.creditAplDt }" 
			+"		  ,#{data.orderNo     }" 
			+"		  ,#{data.vanDivider  }" 
			+"		  ,#{data.gsPoint     }"      
			+"		  ,''"      
			+"  )"
			+" </foreach>"
			+" SELECT * FROM DUAL"
			+"</script>"
			;

	public static final String DELETE_SQL =""
			+"<script>"
			+"DELETE FROM SETTLE_GS WHERE WORK_DT = #{workDt} AND JOB_DIVIDER = #{jobDivider}"
			+"</script>";

// TODO : 대사 코드 정의 
// TODO : 임시로 소스에 하드코딩 추후 R2 admin_code에서 매핑 예정
//	-- 상태 정의
//	-- STS-0001 : 일치
//	-- STS-0002 : 불일치
//	-- STS-0003 : KPC에만존재
//	-- STS-0004 : GS에만존재
//	-- STS-0005 : HM에만존재
//	-- 상세 상태 정의
//	-- STL-0001 : KPC에만존재
//	-- STL-0002 : GS에만존재
//	-- STL-0003 : 승인번호 다름
//	-- STL-0004 : 승인일자 다름 (승인일시+승인시간)
//	-- STL-0005 : 금액 다름
//	-- STL-0006 : 결제 구분 다름
//	-- STL-0007 : 카드번호다름	
//	-- STL-0008 사용 포인트 다름
//	-- STL-0009 스토어 코드 다름	
//	-- STL-0010 HM 에만 존재	
	/*
	public static final String INSERT_GSSM_SETTLE_SQL =""
		   +"INSERT INTO SETTLE_RESULT"
		   +" SELECT (SELECT NVL(MAX(TO_NUMBER(SEQ)), 0)   FROM SETTLE_RESULT WHERE WORK_DT = A.WORK_DT) + ROWNUM"
		   +"      , #{jobDivider}"
		   +"      , DEAL_NO"
		   +"      , APPROVAL_NO"
		   +"      , MERCHANTID"
		   +"      , DEAL_TYPE"
		   +"      , DEAL_DIVIDER"
		   +"      , DEAL_AMT"
		   +"      , #{settleDate}"
		   +"      , SEQ"
		   +"      , CASE WHEN STL1 = 'STL-0001'"
		   +"             THEN 'STS-0003'"
		   +"             WHEN STL2 = 'STL-0002'"
		   +"             THEN 'STS-0004'"
		   +"             WHEN STL1 || STL2 || STL3 || STL4 || STL5 || STL6 || STL7 IS NOT NULL"
		   +"             THEN 'STS-0002'"
		   +"             ELSE 'STS-0001'"
		   +"        END"
		   +"      , CASE WHEN STL1 IS NOT NULL"
		   +"             THEN STL1"
		   +"             WHEN STL2 IS NOT NULL"
		   +"             THEN STL2"
		   +"             WHEN STL3 || STL4 || STL5 || STL6 || STL7 IS NOT NULL"
		   +"             THEN DECODE( STL3 , NULL , '' , STL3 || ',') || DECODE( STL4 , NULL , '' , STL4 || ',')"
		   +"               || DECODE( STL5 , NULL , '' , STL5 || ',') || DECODE( STL6 , NULL , '' , STL6 || ',')"
		   +"               || DECODE( STL7 , NULL , '' , STL7 || ',')"
		   +"             ELSE ''"
		   +"        END"
		   +"      , SYSDATE"
		   +"      , APPROVAL_DT"
		   +"      , APPROVAL_TIME"
		   +"    FROM ("
		   +"          SELECT DECODE( A.CARD_NO , NULL , 'STL-0001' , '') STL1"
		   +"               , DECODE( B.CARD_NO , NULL , 'STL-0002' , '') STL2"
		   +"               , DECODE( A.APPROVAL_NO , B.APPROVAL_NO, '' , 'STL-0003' ) STL3"
		   +"               , DECODE( A.SALE_DT , B.SALE_DT , '' , 'STL-0004') STL4"
		   +"               , DECODE( A.DEAL_AMT , B.DEAL_AMT , '' , 'STL-0005') STL5"
		   +"               , DECODE( A.DEAL_DIVIDER , B.DEAL_DIVIDER , '' , 'STL-0006') STL6"
		   +"               , DECODE( A.CARD_NO , B.CARD_NO , '' , 'STL-0007') STL7"
           +"               , NVL(A.DEAL_NO,B.DEAL_NO) DEAL_NO"
           +"               , NVL(A.APPROVAL_NO , B.APPROVAL_NO) APPROVAL_NO"
           +"               , B.MERCHANTID"
           +"               , NVL(A.WORK_DT , B.SALE_DT) WORK_DT"
           +"               , A.SEQ"		   
           +"               , NVL(B.DEAL_TYPE ,  A.DEAL_TYPE) DEAL_TYPE"		   
           +"               , NVL(B.DEAL_DIVIDER , A.DEAL_DIVIDER) DEAL_DIVIDER"		   
           +"               , NVL(A.DEAL_AMT,B.DEAL_AMT) DEAL_AMT"		   
           +"               , NVL(B.APPROVAL_DT,A.APPROVAL_DT) APPROVAL_DT"		   
           +"               , NVL(B.APPROVAL_TIME,A.APPROVAL_TIME) APPROVAL_TIME"		   
		   +"            FROM ("
		   +"                   SELECT *"
		   +"                     FROM SETTLE_GS"
		   +"                    WHERE SALE_DT = TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                      AND JOB_DIVIDER = #{jobDivider}"
		   +"                 ) A"
		   +"            FULL OUTER JOIN"
		   +"                ("
		   +"                SELECT  SALESDATE SALE_DT"
		   +"                        ,BRANCHCODE STORE_CD"
		   +"                        ,ORDERNO DEAL_NO"
		   +"                        ,APLNO APPROVAL_NO"
		   +"                        ,APLDATE APPROVAL_DT"
		   +"                        ,APLTIME APPROVAL_TIME"
		   +"                        ,A.GIFT_NO"
		   +"                        ,(SELECT EXTEND_NO"
		   +"                            FROM GIFTEXTEND"
		   +"                           WHERE GIFT_NO = A.GIFT_NO) AS CARD_NO"
		   +"                        ,ORDERAMT DEAL_AMT"
		   +"                        ,TTYPE DEAL_TYPE"
		   +"                        ,ATYPE DEAL_DIVIDER"
		   +"                        ,MERCHANTID"
		   +"                  FROM   (SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 APLDATE,"
		   +"                                 APLTIME,"
		   +"                                 (SELECT MAX(B.GIFT_NO)"
		   +"                                  FROM   ORDERDETAIL A,"
		   +"                                         (SELECT GIFT_NO,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_NO,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
		   +"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
		   +"                                 (SELECT MAX(B.GIFT_CHECK)"
		   +"                                  FROM   ORDERDETAIL A,"
		   +"                                         (SELECT GIFT_CHECK,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
		   +"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
		   +"                                 ORDERAMT,"
		   +"                                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
		   +"                                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
		   +"                                 '0' PTYPE,"
		   +"                                 MERCHANTID"
		   +"                          FROM   ORDERLIST_POS"		   
		   +"                          WHERE  MERCHANTID = #{pgOnline}"
		   +"   						AND    MERCHANTID != BRANCHCODE"
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          UNION ALL"
		   +"                          SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 APLORDERNO ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 APLDATE,"
		   +"                                 APLTIME,"
		   +"                                 (SELECT MAX(TICKET_SNO)"
		   +"                                  FROM   ACTIVE_APL_DETAIL"
		   +"                                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
		   +"                                 (SELECT MAX(B.GIFT_CHECK)"
		   +"                                  FROM   ACTIVE_APL_DETAIL A,"
		   +"                                         (SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.TICKET_SNO = B.GIFT_NO"
		   +"                                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
		   +"                                 (SELECT CREATE_AMT"
		   +"                                  FROM   (SELECT GIFT_NO,"
		   +"                                                 CREATE_AMT"
		   +"                                          FROM   GIFTDELETE ) A"
		   +"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		   +"                                          FROM   ACTIVE_APL_DETAIL A"
		   +"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
		   +"                                  UNION ALL"
		   +"                                  SELECT CREATE_AMT"
		   +"                                  FROM   (SELECT GIFT_NO,"
		   +"                                                 CREATE_AMT"
		   +"                                          FROM   GIFTCREATE ) A"
		   +"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		   +"                                          FROM   ACTIVE_APL_DETAIL A"
		   +"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
		   +"                                 'ACT' TTYPE,"
		   +"                                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
		   +"                                 NVL(PAY_METHDO, '0') PTYPE,"
		   +"                                 APLONLINEID MERCHANTID"
		   +"                          FROM   ACTIVE_APPROVAL"
		   +"                          WHERE  APLONLINEID = #{otisOnline}"
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          UNION ALL"
		   +"                          SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 APLORDERNO ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
		   +"                                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
		   +"                                 GIFT_NO,"
		   +"                                 (SELECT GIFT_CHECK"
		   +"                                  FROM   (SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTDELETE)"
		   +"                                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
		   +"                                 RC_AMT ORDERAMT,"
		   +"                                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TS1', 'TRN') TTYPE,"
		   +"                                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TS1', '0') ATYPE,"
		   +"                                 NVL(PAY_METHDO, '0') PTYPE,"
           +"                                 APLONLINEID MERCHANTID"
		   +"                          FROM   RC_APPROVAL"
		   +"                          WHERE  APLONLINEID = #{otisOnline}"
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          AND    APLSTATUS IN ('O1','D1','TS1') ) A"
		   +"                  ) B"
		   +"              ON A.SALE_DT = B.SALE_DT"
		   +"             AND A.STORE_CD = B.STORE_CD"
		   +"             AND A.DEAL_NO = B.DEAL_NO"
		   +"             AND A.DEAL_TYPE = B.DEAL_TYPE"
		   +"             AND A.DEAL_DIVIDER = B.DEAL_DIVIDER"
		   +"            ) A "
		   +"";
	*/
	/*
	public static final String INSERT_GSPOP_SETTLE_SQL =""
			+"INSERT INTO SETTLE_RESULT"
			+" SELECT (SELECT NVL(MAX(TO_NUMBER(SEQ)), 0)   FROM SETTLE_RESULT WHERE WORK_DT = A.WORK_DT) + ROWNUM"
			+"      , #{jobDivider}"
			+"      , DEAL_NO"
			+"      , APPROVAL_NO"
			+"      , MERCHANTID"
			+"      , DEAL_TYPE"
			+"      , DEAL_DIVIDER"
			+"      , DEAL_AMT"
			+"      , #{settleDate}"
			+"      , SEQ"
			+"      , CASE WHEN STL1 = 'STL-0001'"
			+"             THEN 'STS-0003'"
			+"             WHEN STL2 = 'STL-0002'"
			+"             THEN 'STS-0004'"
			+"             WHEN STL1 || STL2 || STL3 || STL4 || STL5 || STL6 || STL7 IS NOT NULL"
			+"             THEN 'STS-0002'"
			+"             ELSE 'STS-0001'"
			+"        END"
			+"      , CASE WHEN STL1 IS NOT NULL"
			+"             THEN STL1"
			+"             WHEN STL2 IS NOT NULL"
			+"             THEN STL2"
			+"             WHEN STL3 || STL4 || STL5 || STL6 || STL7 IS NOT NULL"
			+"             THEN DECODE( STL3 , NULL , '' , STL3 || ',') || DECODE( STL4 , NULL , '' , STL4 || ',')"
			+"               || DECODE( STL5 , NULL , '' , STL5 || ',') || DECODE( STL6 , NULL , '' , STL6 || ',')"
			+"               || DECODE( STL7 , NULL , '' , STL7 || ',')"
			+"             ELSE ''"
			+"        END"
			+"      , SYSDATE"
			+"      , APPROVAL_DT"
			+"      , APPROVAL_TIME"
			+"    FROM ("
			+"          SELECT DECODE( A.CARD_NO , NULL , 'STL-0001' , '') STL1"
			+"               , DECODE( B.CARD_NO , NULL , 'STL-0002' , '') STL2"
			+"               , DECODE( A.APPROVAL_NO , B.APPROVAL_NO, '' , 'STL-0003' ) STL3"
			+"               , DECODE( A.SALE_DT , B.SALE_DT , '' , 'STL-0004') STL4"
			+"               , DECODE( A.DEAL_AMT , B.DEAL_AMT , '' , 'STL-0005') STL5"
			+"               , DECODE( A.DEAL_DIVIDER , B.DEAL_DIVIDER , '' , 'STL-0006') STL6"
			+"               , DECODE( A.CARD_NO , B.CARD_NO , '' , 'STL-0007') STL7"
			+"               , NVL(A.DEAL_NO,B.DEAL_NO) DEAL_NO"
			+"               , NVL(A.APPROVAL_NO , B.APPROVAL_NO) APPROVAL_NO"
			+"               , B.MERCHANTID"
			+"               , NVL(A.WORK_DT , B.SALE_DT) WORK_DT"
			+"               , A.SEQ"		   
	        +"               , NVL(B.DEAL_TYPE ,  A.DEAL_TYPE) DEAL_TYPE"		   
	        +"               , NVL(B.DEAL_DIVIDER , A.DEAL_DIVIDER) DEAL_DIVIDER"	
			+"               , NVL(A.DEAL_AMT,B.DEAL_AMT) DEAL_AMT"		   
	        +"               , NVL(B.APPROVAL_DT,A.APPROVAL_DT) APPROVAL_DT"		   
	        +"               , NVL(B.APPROVAL_TIME,A.APPROVAL_TIME) APPROVAL_TIME"				
			+"            FROM ("
			+"                   SELECT *"
			+"                     FROM SETTLE_GS"
			+"                    WHERE SALE_DT = TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                      AND JOB_DIVIDER = #{jobDivider}"
			+"                 ) A"
			+"            FULL OUTER JOIN"
			+"                ("
			+"                SELECT  SALESDATE SALE_DT"
			+"                        ,BRANCHCODE STORE_CD"
			+"                        ,ORDERNO DEAL_NO"
			+"                        ,APLNO APPROVAL_NO"
			+"                        ,APLDATE APPROVAL_DT"
			+"                        ,APLTIME APPROVAL_TIME"
			+"                        ,A.GIFT_NO"
			+"                        ,(SELECT EXTEND_NO"
			+"                            FROM GIFTEXTEND"
			+"                           WHERE GIFT_NO = A.GIFT_NO) AS CARD_NO"
			+"                        ,ORDERAMT DEAL_AMT"
			+"                        ,TTYPE DEAL_TYPE"
			+"                        ,ATYPE DEAL_DIVIDER"
			+"                        ,MERCHANTID"
			+"                  FROM   (SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 ORDERNO,"
			+"                                 APLNO,"
			+"                                 APLDATE,"
			+"                                 APLTIME,"
			+"                                 (SELECT MAX(B.GIFT_NO)"
			+"                                  FROM   ORDERDETAIL A,"
			+"                                         (SELECT GIFT_NO,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_NO,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
			+"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
			+"                                 (SELECT MAX(B.GIFT_CHECK)"
			+"                                  FROM   ORDERDETAIL A,"
			+"                                         (SELECT GIFT_CHECK,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
			+"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
			+"                                 ORDERAMT,"
			+"                                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
			+"                                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
			+"                                 '0' PTYPE,"
			+"                                 MERCHANTID"
			+"                          FROM   ORDERLIST_POS"
			+"                          WHERE  MERCHANTID = #{pgOnline}"
			+"							AND    MERCHANTID != BRANCHCODE"
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          UNION ALL"
			+"                          SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 APLORDERNO ORDERNO,"
			+"                                 APLNO,"
			+"                                 APLDATE,"
			+"                                 APLTIME,"
			+"                                 (SELECT MAX(TICKET_SNO)"
			+"                                  FROM   ACTIVE_APL_DETAIL"
			+"                                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
			+"                                 (SELECT MAX(B.GIFT_CHECK)"
			+"                                  FROM   ACTIVE_APL_DETAIL A,"
			+"                                         (SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.TICKET_SNO = B.GIFT_NO"
			+"                                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
			+"                                 (SELECT CREATE_AMT"
			+"                                  FROM   (SELECT GIFT_NO,"
			+"                                                 CREATE_AMT"
			+"                                          FROM   GIFTDELETE ) A"
			+"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
			+"                                          FROM   ACTIVE_APL_DETAIL A"
			+"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
			+"                                  UNION ALL"
			+"                                  SELECT CREATE_AMT"
			+"                                  FROM   (SELECT GIFT_NO,"
			+"                                                 CREATE_AMT"
			+"                                          FROM   GIFTCREATE ) A"
			+"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
			+"                                          FROM   ACTIVE_APL_DETAIL A"
			+"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
			+"                                 'ACT' TTYPE,"
			+"                                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
			+"                                 NVL(PAY_METHDO, '0') PTYPE,"
			+"                                 APLONLINEID MERCHANTID"
			+"                          FROM   ACTIVE_APPROVAL"
			+"                          WHERE  APLONLINEID = #{otisOnline}"
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          UNION ALL"
			+"                          SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 APLORDERNO ORDERNO,"
			+"                                 APLNO,"
			+"                                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
			+"                                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
			+"                                 GIFT_NO,"
			+"                                 (SELECT GIFT_CHECK"
			+"                                  FROM   (SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTDELETE)"
			+"                                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
			+"                                 RC_AMT ORDERAMT,"
			+"                                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TT1', 'TRN') TTYPE,"
			+"                                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TT1', '0') ATYPE,"
			+"                                 NVL(PAY_METHDO, '0') PTYPE,"
	        +"                                 APLONLINEID MERCHANTID"
			+"                          FROM   RC_APPROVAL"
			+"                          WHERE  APLONLINEID = #{otisOnline}"
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          AND    APLSTATUS IN ('O1','D1','TT1') ) A"
			+"                  ) B"
			+"              ON A.SALE_DT      = B.SALE_DT"
			+"             AND A.STORE_CD     = B.STORE_CD"
			+"             AND A.DEAL_NO      = B.DEAL_NO"
			+"             AND A.DEAL_TYPE    = B.DEAL_TYPE"
			+"             AND A.DEAL_DIVIDER = B.DEAL_DIVIDER"
			+"            ) A "
			+"";
	*/
	public static final String SELECT_SETTLE_GSPOP_SQL = "SELECT DECODE( A.CARD_NO , NULL , 'STL-0001' , '') STL1"
			+"               , DECODE( B.CARD_NO , NULL , 'STL-0002' , '') STL2"
			+"               , DECODE( A.APPROVAL_NO , B.APPROVAL_NO, '' , 'STL-0003' ) STL3"
			+"               , DECODE( A.SALE_DT , B.SALE_DT , '' , 'STL-0004') STL4"
			+"               , DECODE( A.DEAL_AMT , B.DEAL_AMT , '' , 'STL-0005') STL5"
			+"               , DECODE( A.DEAL_DIVIDER , B.DEAL_DIVIDER , '' , 'STL-0006') STL6"
			+"               , DECODE( A.CARD_NO , B.CARD_NO , '' , 'STL-0007') STL7"
			+"               , NVL(A.DEAL_NO,B.DEAL_NO) DEAL_NO"
			+"               , NVL(A.APPROVAL_NO , B.APPROVAL_NO) APPROVAL_NO"
			+"               , B.MERCHANTID"
			+"               , NVL(A.WORK_DT , B.SALE_DT) WORK_DT"
			+"               , A.SEQ"		   
	        +"               , NVL(B.DEAL_TYPE ,  A.DEAL_TYPE) DEAL_TYPE"		   
	        +"               , NVL(B.DEAL_DIVIDER , A.DEAL_DIVIDER) DEAL_DIVIDER"	
			+"               , NVL(A.DEAL_AMT,B.DEAL_AMT) DEAL_AMT"		   
	        +"               , NVL(B.APPROVAL_DT,A.APPROVAL_DT) APPROVAL_DT"		   
	        +"               , NVL(B.APPROVAL_TIME,A.APPROVAL_TIME) APPROVAL_TIME"				
			+"            FROM ("
			+"                   SELECT *"
			+"                     FROM SETTLE_GS"
			+"                    WHERE SALE_DT = TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                      AND JOB_DIVIDER = #{jobDivider}"
			+"                 ) A"
			+"            FULL OUTER JOIN"
			+"                ("
			+"                SELECT  SALESDATE SALE_DT"
			+"                        ,BRANCHCODE STORE_CD"
			+"                        ,ORDERNO DEAL_NO"
			+"                        ,APLNO APPROVAL_NO"
			+"                        ,APLDATE APPROVAL_DT"
			+"                        ,APLTIME APPROVAL_TIME"
			+"                        ,A.GIFT_NO"
			+"                        ,(SELECT EXTEND_NO"
			+"                            FROM GIFTEXTEND"
			+"                           WHERE GIFT_NO = A.GIFT_NO) AS CARD_NO"
			+"                        ,ORDERAMT DEAL_AMT"
			+"                        ,TTYPE DEAL_TYPE"
			+"                        ,ATYPE DEAL_DIVIDER"
			+"                        ,MERCHANTID"
			+"                  FROM   (SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 ORDERNO,"
			+"                                 APLNO,"
			+"                                 APLDATE,"
			+"                                 APLTIME,"
			+"                                 (SELECT MAX(B.GIFT_NO)"
			+"                                  FROM   ORDERDETAIL A,"
			+"                                         (SELECT GIFT_NO,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_NO,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
			+"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
			+"                                 (SELECT MAX(B.GIFT_CHECK)"
			+"                                  FROM   ORDERDETAIL A,"
			+"                                         (SELECT GIFT_CHECK,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 SEQ_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
			+"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
			+"                                 ORDERAMT,"
			+"                                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
			+"                                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
			+"                                 '0' PTYPE,"
			+"                                 MERCHANTID"
			+"                          FROM   ORDERLIST_POS"
			+"                          WHERE  MERCHANTID = #{pgOnline}"
			+"							AND    MERCHANTID != BRANCHCODE"
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          UNION ALL"
			+"                          SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 APLORDERNO ORDERNO,"
			+"                                 APLNO,"
			+"                                 APLDATE,"
			+"                                 APLTIME,"
			+"                                 (SELECT MAX(TICKET_SNO)"
			+"                                  FROM   ACTIVE_APL_DETAIL"
			+"                                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
			+"                                 (SELECT MAX(B.GIFT_CHECK)"
			+"                                  FROM   ACTIVE_APL_DETAIL A,"
			+"                                         (SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTDELETE) B"
			+"                                  WHERE  A.TICKET_SNO = B.GIFT_NO"
			+"                                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
			+"                                 (SELECT CREATE_AMT"
			+"                                  FROM   (SELECT GIFT_NO,"
			+"                                                 CREATE_AMT"
			+"                                          FROM   GIFTDELETE ) A"
			+"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
			+"                                          FROM   ACTIVE_APL_DETAIL A"
			+"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
			+"                                  UNION ALL"
			+"                                  SELECT CREATE_AMT"
			+"                                  FROM   (SELECT GIFT_NO,"
			+"                                                 CREATE_AMT"
			+"                                          FROM   GIFTCREATE ) A"
			+"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
			+"                                          FROM   ACTIVE_APL_DETAIL A"
			+"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
			+"                                 'ACT' TTYPE,"
			+"                                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
			+"                                 NVL(PAY_METHDO, '0') PTYPE,"
			+"                                 APLONLINEID MERCHANTID"
			+"                          FROM   ACTIVE_APPROVAL"
			+"                          WHERE  APLONLINEID = #{otisOnline}"
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          UNION ALL"
			+"                          SELECT SALESDATE,"
			+"                                 BRANCHCODE,"
			+"                                 APLORDERNO ORDERNO,"
			+"                                 APLNO,"
			+"                                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
			+"                                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
			+"                                 GIFT_NO,"
			+"                                 (SELECT GIFT_CHECK"
			+"                                  FROM   (SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTCREATE"
			+"                                          UNION ALL"
			+"                                          SELECT GIFT_CHECK,"
			+"                                                 GIFT_NO"
			+"                                          FROM   GIFTDELETE)"
			+"                                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
			+"                                 RC_AMT ORDERAMT,"
			+"                                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TT1', 'TRN') TTYPE,"
			+"                                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TT1', '0') ATYPE,"
			+"                                 NVL(PAY_METHDO, '0') PTYPE,"
	        +"                                 APLONLINEID MERCHANTID"
			+"                          FROM   RC_APPROVAL"
			+"                          WHERE  APLONLINEID = #{otisOnline}"
			+ "							AND    BRANCHCODE IS NOT NULL"	
			+"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
			+"                          AND    APLSTATUS IN ('O1','D1','TT1') ) A"
			+"                  ) B"
			+"              ON A.SALE_DT      = B.SALE_DT"
			+"             AND A.STORE_CD     = B.STORE_CD"
			+"             AND A.DEAL_NO      = B.DEAL_NO"
			+"             AND A.DEAL_TYPE    = B.DEAL_TYPE"
			+"             AND A.DEAL_DIVIDER = B.DEAL_DIVIDER"
			+ "";
	
	public static final String DELETE_SETTLE_SQL =""
			+"<script>"
			+"DELETE FROM SETTLE_RESULT WHERE WORK_DT = #{settleDate} AND JOB_DIVIDER = #{jobDivider}"
			+"</script>";
	
	public static final String INSERT_SETTLE_SQL="<script>"
			+" INSERT ALL"
			+" <foreach collection='gsSettleResult' item='data' index='index' separator='' close=''>"												
			+ " INTO SETTLE_RESULT VALUES"
			+ " (#{data.seq}"
			+ " ,#{data.jobDivider}"
			+ " ,#{data.orderNo, jdbcType=VARCHAR}"
			+ " ,#{data.approvalNo}"
			+ " ,#{data.svcConnId, jdbcType=VARCHAR}"
			+ " ,#{data.dealType}"
			+ " ,#{data.dealDivider, jdbcType=VARCHAR}"
			+ " ,#{data.orderAmt}"
			+ " ,#{data.workDt}"
			+ " ,#{data.settleSeq, jdbcType=VARCHAR}"
			+ " ,#{data.status}"
			+ " ,#{data.statusDesc}"
			+ " ,#{data.createDt}"
			+ " ,#{data.approvalDt}"
			+ " ,#{data.approvalTime}"												
			+ " ) "
	        +"</foreach>"
	        +" SELECT * FROM DUAL"
	        +"</script>";

	public static final String SELECT_SETTLE_GSSM_SQL =
			"SELECT DECODE( A.CARD_NO , NULL , 'STL-0001' , '') STL1"
		   +"               , DECODE( B.CARD_NO , NULL , 'STL-0002' , '') STL2"
		   +"               , DECODE( A.APPROVAL_NO , B.APPROVAL_NO, '' , 'STL-0003' ) STL3"
		   +"               , DECODE( A.SALE_DT , B.SALE_DT , '' , 'STL-0004') STL4"
		   +"               , DECODE( A.DEAL_AMT , B.DEAL_AMT , '' , 'STL-0005') STL5"
		   +"               , DECODE( A.DEAL_DIVIDER , B.DEAL_DIVIDER , '' , 'STL-0006') STL6"
		   +"               , DECODE( A.CARD_NO , B.CARD_NO , '' , 'STL-0007') STL7"
           +"               , NVL(A.DEAL_NO,B.DEAL_NO) DEAL_NO"
           +"               , NVL(A.APPROVAL_NO , B.APPROVAL_NO) APPROVAL_NO"
           +"               , B.MERCHANTID"
           +"               , NVL(A.WORK_DT , B.SALE_DT) WORK_DT"
           +"               , A.SEQ"		   
           +"               , NVL(B.DEAL_TYPE ,  A.DEAL_TYPE) DEAL_TYPE"		   
           +"               , NVL(B.DEAL_DIVIDER , A.DEAL_DIVIDER) DEAL_DIVIDER"		   
           +"               , NVL(A.DEAL_AMT,B.DEAL_AMT) DEAL_AMT"		   
           +"               , NVL(B.APPROVAL_DT,A.APPROVAL_DT) APPROVAL_DT"		   
           +"               , NVL(B.APPROVAL_TIME,A.APPROVAL_TIME) APPROVAL_TIME"		   
		   +"            FROM ("
		   +"                   SELECT *"
		   +"                     FROM SETTLE_GS"
		   +"                    WHERE SALE_DT = TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                      AND JOB_DIVIDER = #{jobDivider}"
		   +"                 ) A"
		   +"            FULL OUTER JOIN"
		   +"                ("
		   +"                SELECT  SALESDATE SALE_DT"
		   +"                        ,BRANCHCODE STORE_CD"
		   +"                        ,ORDERNO DEAL_NO"
		   +"                        ,APLNO APPROVAL_NO"
		   +"                        ,APLDATE APPROVAL_DT"
		   +"                        ,APLTIME APPROVAL_TIME"
		   +"                        ,A.GIFT_NO"
		   +"                        ,(SELECT EXTEND_NO"
		   +"                            FROM GIFTEXTEND"
		   +"                           WHERE GIFT_NO = A.GIFT_NO) AS CARD_NO"
		   +"                        ,ORDERAMT DEAL_AMT"
		   +"                        ,TTYPE DEAL_TYPE"
		   +"                        ,ATYPE DEAL_DIVIDER"
		   +"                        ,MERCHANTID"
		   +"                  FROM   (SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 APLDATE,"
		   +"                                 APLTIME,"
		   +"                                 (SELECT MAX(B.GIFT_NO)"
		   +"                                  FROM   ORDERDETAIL A,"
		   +"                                         (SELECT GIFT_NO,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_NO,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
		   +"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_NO,"
		   +"                                 (SELECT MAX(B.GIFT_CHECK)"
		   +"                                  FROM   ORDERDETAIL A,"
		   +"                                         (SELECT GIFT_CHECK,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 SEQ_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.C_SERIAL = B.SEQ_NO"
		   +"                                  AND    A.TRANSID = ORDERLIST_POS.TRANSID ) GIFT_CHECK,"
		   +"                                 ORDERAMT,"
		   +"                                 DECODE(RESULTCODE, 'O1', 'PAY', 'R1', 'REF', 'D1', 'PAY', 'T1', 'REF') TTYPE,"
		   +"                                 DECODE(RESULTCODE, 'O1', '0', 'R1', '0', 'D1', '9', 'T1', '9') ATYPE,"
		   +"                                 '0' PTYPE,"
		   +"                                 MERCHANTID"
		   +"                          FROM   ORDERLIST_POS"		   
		   +"                          WHERE  MERCHANTID = #{pgOnline}"
		   +"   						AND    MERCHANTID != BRANCHCODE"
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          UNION ALL"
		   +"                          SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 APLORDERNO ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 APLDATE,"
		   +"                                 APLTIME,"
		   +"                                 (SELECT MAX(TICKET_SNO)"
		   +"                                  FROM   ACTIVE_APL_DETAIL"
		   +"                                  WHERE  APLID = ACTIVE_APPROVAL.APLID ) GIFT_NO,"
		   +"                                 (SELECT MAX(B.GIFT_CHECK)"
		   +"                                  FROM   ACTIVE_APL_DETAIL A,"
		   +"                                         (SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTDELETE) B"
		   +"                                  WHERE  A.TICKET_SNO = B.GIFT_NO"
		   +"                                  AND    A.APLID = ACTIVE_APPROVAL.APLID ) GIFT_CHECK,"
		   +"                                 (SELECT CREATE_AMT"
		   +"                                  FROM   (SELECT GIFT_NO,"
		   +"                                                 CREATE_AMT"
		   +"                                          FROM   GIFTDELETE ) A"
		   +"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		   +"                                          FROM   ACTIVE_APL_DETAIL A"
		   +"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID )"
		   +"                                  UNION ALL"
		   +"                                  SELECT CREATE_AMT"
		   +"                                  FROM   (SELECT GIFT_NO,"
		   +"                                                 CREATE_AMT"
		   +"                                          FROM   GIFTCREATE ) A"
		   +"                                  WHERE  GIFT_NO = (SELECT MAX(TICKET_SNO)"
		   +"                                          FROM   ACTIVE_APL_DETAIL A"
		   +"                                          WHERE  APLID = ACTIVE_APPROVAL.APLID ) )ORDERAMT,"
		   +"                                 'ACT' TTYPE,"
		   +"                                 DECODE(APLSTATUS, '1', '0', '2', '9') ATYPE,"
		   +"                                 NVL(PAY_METHDO, '0') PTYPE,"
		   +"                                 APLONLINEID MERCHANTID"
		   +"                          FROM   ACTIVE_APPROVAL"
		   +"                          WHERE  APLONLINEID = #{otisOnline}"
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          UNION ALL"
		   +"                          SELECT SALESDATE,"
		   +"                                 BRANCHCODE,"
		   +"                                 APLORDERNO ORDERNO,"
		   +"                                 APLNO,"
		   +"                                 TO_CHAR(APLDATE, 'YYYYMMDD') APLDATE,"
		   +"                                 TO_CHAR(APLDATE, 'HH24MISS') APLTIME,"
		   +"                                 GIFT_NO,"
		   +"                                 (SELECT GIFT_CHECK"
		   +"                                  FROM   (SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTCREATE"
		   +"                                          UNION ALL"
		   +"                                          SELECT GIFT_CHECK,"
		   +"                                                 GIFT_NO"
		   +"                                          FROM   GIFTDELETE)"
		   +"                                  WHERE  GIFT_NO = RC_APPROVAL.GIFT_NO ) GIFT_CHECK,"
		   +"                                 RC_AMT ORDERAMT,"
		   +"                                 DECODE(APLSTATUS, 'O1', 'CHR', 'D1', 'CHR', 'TS1', 'TRN') TTYPE,"
		   +"                                 DECODE(APLSTATUS, 'O1', '0', 'D1', '9', 'TS1', '0') ATYPE,"
		   +"                                 NVL(PAY_METHDO, '0') PTYPE,"
           +"                                 APLONLINEID MERCHANTID"
		   +"                          FROM   RC_APPROVAL"
		   +"                          WHERE  APLONLINEID = #{otisOnline}"
		   + "						   AND    BRANCHCODE IS NOT NULL"	
		   +"                          AND    SALESDATE =  TO_CHAR(TO_DATE(#{settleDate}) - 1 , 'YYYYMMDD')"
		   +"                          AND    APLSTATUS IN ('O1','D1','TS1') ) A"
		   +"                  ) B"
		   +"              ON A.SALE_DT = B.SALE_DT"
		   +"             AND A.STORE_CD = B.STORE_CD"
		   +"             AND A.DEAL_NO = B.DEAL_NO"
		   +"             AND A.DEAL_TYPE = B.DEAL_TYPE"
		   +"             AND A.DEAL_DIVIDER = B.DEAL_DIVIDER";
	
	public static final String SELECT_MAX_SEQ = "SELECT (NVL(MAX(TO_NUMBER(SEQ)), 0)+1) FROM SETTLE_RESULT";
	
	@Resource(name="approvalDataSource")
	@Select(GS_POP_SELECT_SQL)
	public List<GsSettlement> gspopSelect(@Param("workDt") String workDt,@Param("otisOnline") String otisOnline,@Param("pgOnline") String pgOnline);

	@Resource(name="approvalDataSource")
	@Select(GS_SM_SELECT_SQL)
	public List<GsSettlement> gssmSelect(@Param("workDt") String workDt,@Param("otisOnline") String otisOnline,@Param("pgOnline") String pgOnline);
	

	@Resource(name="approvalDataSource")
	@Delete(DELETE_SQL)
	public int delete(@Param("workDt")String workDt,@Param("jobDivider") String jobDivider);

	@Resource(name="approvalDataSource")
	@Insert(INSERT_SQL)
	public int insert(@Param("gsSettlementDataList") List<GsSettlement> gsmSettlementDataList,@Param("jobDivider") String jobDivider, @Param("startIdx") int startIdx);

	//@Resource(name="approvalDataSource")
	//@Insert(INSERT_GSSM_SETTLE_SQL)	
	//public int settlementGssm(@Param("jobDivider") String jobDivider, @Param("settleDate")String settleDate,@Param("otisOnline")String otisOnline, @Param("pgOnline")String pgOnline);
	
	//@Resource(name="approvalDataSource")
	//@Insert(INSERT_GSPOP_SETTLE_SQL)	
	//public int settlementGspop(@Param("jobDivider") String jobDivider, @Param("settleDate")String settleDate,@Param("otisOnline")String otisOnline, @Param("pgOnline")String pgOnline);
	
	@Resource(name="approvalDataSource")
	@Delete(DELETE_SETTLE_SQL)	
	public void deleteSettlement(@Param("jobDivider") String jobDivider, @Param("settleDate")String settleDate);
	
	@Resource(name="approvalDataSource")
	@Select(SELECT_SETTLE_GSPOP_SQL)
	public List<GsSettlementSelect> settlementSelectGspop(@Param("jobDivider") String jobDivider, @Param("otisOnline") String otisOnline, @Param("settleDate")String settleDate, @Param("pgOnline")String pgOnline);
	
	@Resource(name="approvalDataSource")
	@Select(SELECT_SETTLE_GSSM_SQL)
	public List<GsSettlementSelect> settlementSelectGssm(@Param("jobDivider") String jobDivider, @Param("otisOnline") String otisOnline, @Param("settleDate")String settleDate, @Param("pgOnline")String pgOnline);
	
	@Resource(name="approvalDataScource")
	@Insert(INSERT_SETTLE_SQL)
	public int settlementInsert(@Param("gsSettleResult") List<GsSettlementResult> gsSettleResult);
	
	@Resource(name="approvalDataSource")
	@Select(SELECT_MAX_SEQ)
	public int selectSeq();
	

	public static final String SELECT_GS_NOT_MATCHED_AMOUNT = "SELECT NVL(SUM(ORDER_AMT), 0) amount FROM"
			+ "													KPC_APPROVAL.SETTLE_RESULT"
			+ "												WHERE SVC_CONN_ID=#{serviceConnId}"
			+ "												AND DEAL_TYPE=#{dealType}"
			+ "												AND WORK_DT BETWEEN #{startDt} AND #{endDt}";
	@Resource(name="approvalDataSource")
	@Select(SELECT_GS_NOT_MATCHED_AMOUNT)	
	public long getGsNotMatchedAmount(@Param(value="serviceConnId") String serviceConnId,
									  @Param(value="startDt") String startDt,
									  @Param(value="endDt") String endDt,
									  @Param(value="dealType") String dealType);
}
