package kr.co.kpcard.billingservice.app.repository.erp.dto;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicUpdate;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="FI_ADOCU")
@DynamicUpdate
@Data
@Getter
@Setter
@IdClass(FiAdocuPK.class)
public class FiAdocuDto implements Serializable{
	private static final long   serialVersionUID = -6107321818952515960L;

	@Id @Column(name="ROW_ID",nullable=false) String rowId;   
	@Id @Column(name="ROW_NO",nullable=false) String rowNo;
	@Column(name="NO_TAX"    ,nullable=false) String noTax;
	@Column(name="CD_PC"     ,nullable=false) String cdPc;
	@Column(name="CD_WDEPT"  ,nullable=false) String cdWdept;
	@Column(name="NO_DOCU"   ,nullable=false) String noDocu;
	@Column(name="NO_DOLINE" ,nullable=false) long   noDoline;
	@Column(name="CD_COMPANY",nullable=false) String cdCompany;
	@Column(name="ID_WRITE")                  String idWrite;
	@Column(name="CD_DOCU")                   String cdDocu;
	@Column(name="DT_ACCT")                   String dtAcct;
	@Column(name="ST_DOCU")                   String stDocu;
	@Column(name="TP_DRCR")                   String tpDrcr;
	@Column(name="CD_ACCT")                   String cdAcct;
	@Column(name="AMT" ,nullable=false)       long   amt;
	@Column(name="CD_PARTNER")                String cdPartner;
	@Column(name="NM_PARTNER")                String nmPartner;
	@Column(name="TP_JOB")                    String tpJob;
	@Column(name="CLS_JOB")                   String clsJob;
	@Column(name="ADS_HD")                    String adsHd;
	@Column(name="NM_CEO")                    String nmCeo;
	@Column(name="DT_START")                  String dtStart;
	@Column(name="DT_END")                    String dtEnd;
	@Column(name="AM_TAXSTD")                 long   amTaxstd;
	@Column(name="AM_ADDTAX")                 long   amAddtax;
	@Column(name="TP_TAX")                    String tpTax;
	@Column(name="NO_COMPANY")                String noCompany;
	@Column(name="DTS_INSERT")                String dtsInsert;
	@Column(name="ID_INSERT")                 String idInsert;
	@Column(name="DTS_UPDATE")                String dtsUpdate;
	@Column(name="ID_UPDATE")                 String idUpdate;
	@Column(name="NM_NOTE")                   String nmNote;
	@Column(name="CD_BIZAREA")                String cdBizarea;
	@Column(name="CD_DEPT")                   String cdDept;
	@Column(name="CD_CC")                     String cdCc;
	@Column(name="CD_PJT")                    String cdPjt;
	@Column(name="CD_FUND")                   String cdFund;
	@Column(name="CD_BUDGET")                 String cdBudget;
	@Column(name="NO_CASH")                   String noCash;
	@Column(name="ST_MUTUAL")                 String stMutual;
	@Column(name="CD_CARD")                   String cdCard;
	@Column(name="NO_DEPOSIT")                String noDeposit;
	@Column(name="CD_BANK")                   String cdBank;
	@Column(name="UCD_MNG1")                  String ucdMng1;
	@Column(name="UCD_MNG2")                  String ucdMng2;
	@Column(name="UCD_MNG3")                  String ucdMng3;
	@Column(name="UCD_MNG4")                  String ucdMng4;
	@Column(name="UCD_MNG5")                  String ucdMng5;
	@Column(name="CD_EMPLOY")                 String cdEmploy;
	@Column(name="CD_MNG")                    String cdMng;
	@Column(name="NO_BDOCU")                  String noBdocu;
	@Column(name="NO_BDOLINE")                long   noBdoline;
	@Column(name="TP_DOCU")                   String tpDocu;
	@Column(name="NO_ACCT")                   long   noAcct;
	@Column(name="TP_TRADE")                  String tpTrade;
	@Column(name="NO_CHECK")                  String noCheck;
	@Column(name="NO_CHECK1")                 String noCheck1;
	@Column(name="CD_EXCH")                   String cdExch;
	@Column(name="RT_EXCH")                   long   rtExch;
	@Column(name="CD_TRADE")                  String cdTrade;
	@Column(name="NO_CHECK2")                 String noCheck2;
	@Column(name="NO_CHECK3")                 String noCheck3;
	@Column(name="NO_CHECK4")                 String noCheck4;
	@Column(name="TP_CROSS")                  String tpCross;
	@Column(name="ERP_CD")                    String erpCd;
	@Column(name="AM_EX")                     long   amEx;
	@Column(name="TP_EXPORT")                 String tpExport;
	@Column(name="NO_TO")                     String noTo;
	@Column(name="DT_SHIPPING")               String dtShipping;
	@Column(name="TP_GUBUN")                  String tpGubun;
	@Column(name="NO_INVOICE")                String noInvoice;
	@Column(name="MD_TAX1")                   String mdTax1;
	@Column(name="NM_ITEM1")                  String nmItem1;
	@Column(name="NM_SIZE1")                  String nmSize1;
	@Column(name="QT_TAX1")                   long   qtTax1;
	@Column(name="AM_PRC1")                   long   amPrc1;
	@Column(name="AM_SUPPLY1")                long   amSupply1;
	@Column(name="AM_TAX1")                   long   amTax1;
	@Column(name="NM_NOTE1")                  String nmNote1;
	@Column(name="NO_ITEM")                   String noItem;
	@Column(name="CD_BIZPLAN")                String cdBizplan;
	@Column(name="CD_BGACCT")                 String cdBgacct;
	@Column(name="CD_MNGD1")                  String cdMngd1;
	@Column(name="NM_MNGD1")                  String nmMngd1;
	@Column(name="CD_MNGD2")                  String cdMngd2;
	@Column(name="NM_MNGD2")                  String nmMngd2;
	@Column(name="CD_MNGD3")                  String cdMngd3;
	@Column(name="NM_MNGD3")                  String nmMngd3;
	@Column(name="CD_MNGD4")                  String cdMngd4;
	@Column(name="NM_MNGD4")                  String nmMngd4;
	@Column(name="CD_MNGD5")                  String cdMngd5;
	@Column(name="NM_MNGD5")                  String nmMngd5;
	@Column(name="CD_MNGD6")                  String cdmngd6;
	@Column(name="NM_MNGD6")                  String nmMngd6;
	@Column(name="CD_MNGD7")                  String cdMngd7;
	@Column(name="NM_MNGD7")                  String nmMngd7;
	@Column(name="CD_MNGD8")                  String cdMngd8;
	@Column(name="NM_MNGD8")                  String nmMngd8;
	@Column(name="YN_ISS")                    String ynIss;
	@Column(name="FINAL_STATUS")              String finalStatus;
	@Column(name="NO_BILL")                   String noBill;
	@Column(name="TP_BILL")                   String tpBill;
	@Column(name="TP_RECORD")                 String tpRecord;
	@Column(name="TP_ETCACCT")                String tpEtcacct;
	@Column(name="ST_GWARE")                  String stGware;
	@Column(name="SELL_DAM_NM")               String sellDamNm;
	@Column(name="SELL_DAM_EMAIL")            String sellDamEmail;
	@Column(name="SELL_DAM_MOBIL")            String sellDamMobil;
	@Column(name="NM_PUMM")                   String nmPumm;
	@Column(name="JEONJASEND15_YN")           String jeonjasend15Yn;
	@Column(name="DT_WRITE")                  String dtWrite;
	@Column(name="ST_TAX")                    String stTax;
	@Column(name="MD_TAX2")                   String mdTax2;
	@Column(name="NM_ITEM2")                  String nmItem2;
	@Column(name="NM_SIZE2")                  String nmSize2;
	@Column(name="QT_TAX2")                   long   qtTax2;
	@Column(name="AM_PRC2")                   long   amPrc2;
	@Column(name="AM_SUPPLY2")                long   amSupply2;
	@Column(name="AM_TAX2")                   long   amTax2;
	@Column(name="NM_NOTE2")                  String nmNote2;
	@Column(name="MD_TAX3")                   String mdTax3;
	@Column(name="NM_ITEM3")                  String nmItem3;
	@Column(name="NM_SIZE3")                  String nmSize3;
	@Column(name="QT_TAX3")                   long   qtTax3;
	@Column(name="AM_PRC3")                   long   amPrc3;
	@Column(name="AM_SUPPLY3")                long   amSupply3;
	@Column(name="AM_TAX3")                   long   amTax3;
	@Column(name="NM_NOTE3")                  String nmNote3;
	@Column(name="MD_TAX4")                   String mdTax4;
	@Column(name="NM_ITEM4")                  String nmItem4;
	@Column(name="NM_SIZE4")                  String nmSize4;
	@Column(name="QT_TAX4")                   long   qtTax4;
	@Column(name="AM_PRC4")                   long   amPrc4;
	@Column(name="AM_SUPPLY4")                long   amSupply4;
	@Column(name="AM_TAX4")                   long   amTax4;
	@Column(name="NM_NOTE4")                  String nmNote4;
	@Column(name="NO_ASSET")                  String noAsset;
	@Column(name="NM_BIGO")                   String nmBigo;
	@Column(name="NM_PTR")                    String nmPtr;
	@Column(name="EX_HP")                     String exHp;
	@Column(name="EX_EMIL")                   String exEmil;
	@Column(name="NO_BIZTAX")                 String noBiztax;
	@Column(name="YN_IMPORT")                 String ynImport;
	@Column(name="REF_NO_DOCU")               String refNoDocu;
	@Column(name="CD_FX")                     String cdFx;
	@Column(name="FX_BILL")                   String fxBill;
	@Column(name="NO_ISS")                    String noIss;
	@Column(name="TP_EVIDENCE")               String tpEvidence;
	@Column(name="ST_BIZBOX")                 String stBizbox;
	@Column(name="TP_INPUT")                  String tpInput;
	@Column(name="SELL_DAM_TEL")              String sellDamTel;
	@Column(name="TEXT_USERDEF1")             String textUserdef1;
	@Column(name="NO_CAR")                    String noCar;
	@Column(name="NO_CARBODY")                String noCarbody;
	@Column(name="PUMM_NO")                   String pummNo;
	@Column(name="DEC_LEASE")                 String decLease;
	@Column(name="NO_TDOCU")                  String noTdocu;
	@Column(name="NO_TDOLINE")                long   noTdoline;
	@Column(name="CD_BIZCAR")                 String cdBizcar;
	@Column(name="TAX_ID")                    String taxId;
	@Column(name="CD_TAXACCT")                String cdTaxacct;
	
}
