package kr.co.kpcard.backoffice.repository.approval.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import kr.co.kpcard.backoffice.controller.approval.protocol.ApprovalPagination;
import kr.co.kpcard.backoffice.repository.approval.model.ApprovalForList;
import kr.co.kpcard.backoffice.repository.approval.model.Approver;

/**
 * 승인 처리에 필요한 조회 맵퍼
 * Created by @author : MinWook on 2018. 5. 30.
 *
 */
@Mapper
public interface NewApprovalMapper {

	public static final String READ_APPROVER_LIST_BY_MENU_ID = "<script>"
			+ "SELECT"
			+"		 A.EMP_ID as empId "
			+ "		,B.NAME "
			+ "		,B.EMAIL "
			+ "		,A.MENU_ID as menuId "
			+ "		,C.NAME as menuName"
			+ "	FROM KPC_EMP_MENU_INT A "
			+ "		,KPC_EMPLOYE B "
			+ "		,KPC_MENU C "
			+ "	WHERE A.EMP_ID = B.EMP_ID "
			+ "		AND A.MENU_ID = C.MENU_ID "
			+ "		AND A.APPR_FLAG = '1' "
			+ "<if test='logimEmpId!=\"160502\" and logimEmpId!=\"171002\"'> AND A.EMP_ID != #{logimEmpId} </if>"
			+ "		AND A.MENU_ID = #{menuId} "
			+ "</script>";
	@Select(READ_APPROVER_LIST_BY_MENU_ID)
	public List<Approver> readApproverListByMenuId(@Param(value="menuId") String menuId, @Param("logimEmpId") String loginEmpId);

	public static final String READ_APPROVAL_REQUEST_LIST_COUNT = "<script>"
			+ " SELECT count(apprInfo.SEQ) "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.REQ_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.apprEmpName != \"\" '> "
	        + " 			AND apprEmp.NAME LIKE '%' || #{pagination.apprEmpName} || '%' "
	        + "			</if> "
			+"</script>";
	
	@Select(READ_APPROVAL_REQUEST_LIST_COUNT)
	public int readApprovalRequestListCount(@Param(value="pagination")ApprovalPagination pagination);

	public static final String READ_APPROVAL_REQUEST_LIST = "<script>"
			+ " SELECT Z.* FROM ( "
			+ " SELECT ROWNUM as RNUM, X.* FROM ( "
			+ " SELECT "
			+ " 	 apprInfo.SEQ "
			+ " 	,apprInfo.CONTENT_SEQ contentSeq "
			+ "		,apprInfo.WORK_TYPE workType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.WORK_TYPE) workTypeName "
			+ "		,apprInfo.REQ_TYPE as reqType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.REQ_TYPE) reqTypeName "
			+ "		,apprInfo.STATUS "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.STATUS) statusName "
			+ "		,apprInfo.REF_ID refId "
			+ "		,apprInfo.REF_TITLE refTitle "
			+ "		,apprInfo.DESCRIPTION "
			+ "		,apprInfo.KEYWORD "
			+ "		,apprInfo.REQ_EMP_ID reqEmpId "
			+ "		,reqEmp.name reqEmpName "
			+ "		,apprInfo.REQ_DT reqDate "
			+ "		,apprInfo.REQ_MEMO reqMemo "
			+ "		,apprInfo.APPR_EMP_ID apprEmpId "
			+ "		,apprEmp.name apprEmpName "
 			+ "		,apprInfo.APPR_DT apprDate "
			+ "		,apprInfo.APPR_MEMO apprMemo "
			+ "		,apprInfo.CREATE_DT createDate "
			+ "		,apprInfo.UPDATE_DT updateDate "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.REQ_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.apprEmpName != \"\" '> "
	        + " 			AND apprEmp.NAME LIKE '%' || #{pagination.apprEmpName} || '%' "
	        + "			</if> "
	        + " <choose> "
	        + "		<when test='pagination.searchDateOrderType == \"reqDate\"' > "
	        + "			ORDER BY apprInfo.req_dt ${pagination.orderType} "
	        + "		</when> "
	        + "		<when test='pagination.searchDateOrderType == \"apprDate\"' > "
	        + "			ORDER BY apprInfo.appr_dt ${pagination.orderType} nulls last"
	        + "		</when> "
	        + "		<otherwise> "
	        + "			ORDER BY apprInfo.req_dt DESC "
	        + "		</otherwise> "
	        + " </choose> "
			+" ) X "
			+ " WHERE ROWNUM &lt;= (#{pagination.offset} + #{pagination.limit}) "
			+" ) Z "
			+ " WHERE RNUM &gt; #{pagination.offset} "
			+"</script>";
	@Select(READ_APPROVAL_REQUEST_LIST)
	public List<ApprovalForList> readApprovalRequestList(@Param(value="pagination")ApprovalPagination pagination);

	public static final String READ_APPROVAL_REQUEST_LIST_FOR_EXCEL = "<script>"
			+ " SELECT "
			+ " 	 apprInfo.SEQ "
			+ " 	,apprInfo.CONTENT_SEQ contentSeq "
			+ "		,apprInfo.WORK_TYPE workType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.WORK_TYPE) workTypeName "
			+ "		,apprInfo.REQ_TYPE as reqType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.REQ_TYPE) reqTypeName "
			+ "		,apprInfo.STATUS "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.STATUS) statusName "
			+ "		,apprInfo.REF_ID refId "
			+ "		,apprInfo.REF_TITLE refTitle "
			+ "		,apprInfo.DESCRIPTION "
			+ "		,apprInfo.KEYWORD "
			+ "		,apprInfo.REQ_EMP_ID reqEmpId "
			+ "		,reqEmp.name reqEmpName "
			+ "		,apprInfo.REQ_DT reqDate "
			+ "		,apprInfo.REQ_MEMO reqMemo "
			+ "		,apprInfo.APPR_EMP_ID apprEmpId "
			+ "		,apprEmp.name apprEmpName "
			+ "		,apprInfo.APPR_DT apprDate "
			+ "		,apprInfo.APPR_MEMO apprMemo "
			+ "		,apprInfo.CREATE_DT createDate "
			+ "		,apprInfo.UPDATE_DT updateDate "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.REQ_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.apprEmpName != \"\" '> "
	        + " 			AND apprEmp.NAME LIKE '%' || #{pagination.apprEmpName} || '%' "
	        + "			</if> "
	        + " <choose> "
	        + "		<when test='pagination.searchDateOrderType == \"reqDate\"' > "
	        + "			ORDER BY apprInfo.req_dt ${pagination.orderType} "
	        + "		</when> "
	        + "		<when test='pagination.searchDateOrderType == \"apprDate\"' > "
	        + "			ORDER BY apprInfo.appr_dt ${pagination.orderType} nulls last"
	        + "		</when> "
	        + "		<otherwise> "
	        + "			ORDER BY apprInfo.req_dt DESC "
	        + "		</otherwise> "
	        + " </choose> "
			+"</script>";
	@Select(READ_APPROVAL_REQUEST_LIST_FOR_EXCEL)
	public List<ApprovalForList> readApprovalRequestListForExcel(@Param(value="pagination")ApprovalPagination pagination);
	
	public static final String READ_APPROVAL_ANSWER_LIST_COUNT = "<script>"
			+ " SELECT count(apprInfo.SEQ) "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.APPR_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.status != 'ARST-0004' "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='availableApprWorkTypeList.size != 0 '> "
			+ " 			AND apprInfo.work_type in "
			+ " 			<foreach item= \"workType\" index=\"index\" collection=\"availableApprWorkTypeList\" open=\"(\" separator=\",\" close=\")\" > "
			+ " 				#{workType} "
			+ " 			</foreach> "
			+ "			</if> "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.reqEmpName != \"\" '> "
	        + " 			AND reqEmp.NAME LIKE '%' || #{pagination.reqEmpName} || '%' "
	        + "			</if> "  
			+"</script>";
	@Select(READ_APPROVAL_ANSWER_LIST_COUNT)
	public int readApprovalAnswerListCount(@Param(value="pagination")ApprovalPagination pagination, @Param(value="availableApprWorkTypeList")List<String> availableApprWorkTypeList);

	public static final String READ_APPROVAL_ANSWER_LIST = "<script>"
			+ " SELECT Z.* FROM ( "
			+ " SELECT ROWNUM as RNUM, X.* FROM ( "
			+ " SELECT "
			+ " 	 apprInfo.SEQ "
			+ " 	,apprInfo.CONTENT_SEQ as contentSeq "
			+ "		,apprInfo.WORK_TYPE as workType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.WORK_TYPE) workTypeName "
			+ "		,apprInfo.REQ_TYPE as reqType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.REQ_TYPE) reqTypeName "
			+ "		,apprInfo.STATUS "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.STATUS) statusName "
			+ "		,apprInfo.REF_ID as refId "
			+ "		,apprInfo.REF_TITLE as refTitle "
			+ "		,apprInfo.DESCRIPTION "
			+ "		,apprInfo.KEYWORD "
			+ "		,apprInfo.REQ_EMP_ID as reqEmpId "
			+ "		,reqEmp.name as reqEmpName "
			+ "		,apprInfo.REQ_DT AS reqDate "
			+ "		,apprInfo.REQ_MEMO as reqMemo "
			+ "		,apprInfo.APPR_EMP_ID as apprEmpId "
			+ "		,apprEmp.name as apprEmpName "
			+ "		,apprInfo.APPR_DT AS apprDate "
			+ "		,apprInfo.APPR_MEMO as apprMemo "
			+ "		,apprInfo.CREATE_DT as createDate "
			+ "		,apprInfo.UPDATE_DT as updateDate "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.APPR_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.status != 'ARST-0004' "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='availableApprWorkTypeList.size != 0 '> "
			+ " 			AND apprInfo.work_type in "
			+ " 			<foreach item= \"workType\" index=\"index\" collection=\"availableApprWorkTypeList\" open=\"(\" separator=\",\" close=\")\" > "
			+ " 				#{workType} "
			+ " 			</foreach> "
			+ "			</if> "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.reqEmpName != \"\" '> "
	        + " 			AND reqEmp.NAME LIKE '%' || #{pagination.reqEmpName} || '%' "
	        + "			</if> "  
	        + " <choose> "
	        + "		<when test='pagination.searchDateOrderType == \"reqDate\"' > "
	        + "			ORDER BY apprInfo.req_dt ${pagination.orderType} "
	        + "		</when> "
	        + "		<when test='pagination.searchDateOrderType == \"apprDate\"' > "
	        + "			ORDER BY apprInfo.appr_dt ${pagination.orderType} nulls last"
	        + "		</when> "
	        + "		<otherwise> "
	        + "			ORDER BY apprInfo.req_dt DESC "
	        + "		</otherwise> "
	        + " </choose> "
			+" ) X "
			+ " WHERE ROWNUM &lt;= (#{pagination.offset} + #{pagination.limit}) "
			+" ) Z "
			+ " WHERE RNUM &gt; #{pagination.offset} "
			+"</script>";
	@Select(READ_APPROVAL_ANSWER_LIST)
	public List<ApprovalForList> readApprovalAnswerList(@Param(value="pagination")ApprovalPagination pagination, @Param("availableApprWorkTypeList")List<String> availableApprWorkTypeList );

	public static final String READ_APPROVAL_ANSWER_LIST_FOR_EXCEL = "<script>"
			+ " SELECT "
			+ " 	 apprInfo.SEQ "
			+ " 	,apprInfo.CONTENT_SEQ as contentSeq "
			+ "		,apprInfo.WORK_TYPE as workType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.WORK_TYPE) workTypeName "
			+ "		,apprInfo.REQ_TYPE as reqType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.REQ_TYPE) reqTypeName "
			+ "		,apprInfo.STATUS "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.STATUS) statusName "
			+ "		,apprInfo.REF_ID as refId "
			+ "		,apprInfo.REF_TITLE as refTitle "
			+ "		,apprInfo.DESCRIPTION "
			+ "		,apprInfo.KEYWORD "
			+ "		,apprInfo.REQ_EMP_ID as reqEmpId "
			+ "		,reqEmp.name as reqEmpName "
			+ "		,apprInfo.REQ_DT AS reqDate "
			+ "		,apprInfo.REQ_MEMO as reqMemo "
			+ "		,apprInfo.APPR_EMP_ID as apprEmpId "
			+ "		,apprEmp.name as apprEmpName "
			+ "		,apprInfo.APPR_DT AS apprDate "
			+ "		,apprInfo.APPR_MEMO as apprMemo "
			+ "		,apprInfo.CREATE_DT as createDate "
			+ "		,apprInfo.UPDATE_DT as updateDate "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.APPR_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.status != 'ARST-0004' "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='availableApprWorkTypeList.size != 0 '> "
			+ " 			AND apprInfo.work_type in "
			+ " 			<foreach item= \"workType\" index=\"index\" collection=\"availableApprWorkTypeList\" open=\"(\" separator=\",\" close=\")\" > "
			+ " 				#{workType} "
			+ " 			</foreach> "
			+ "			</if> "
			+ " 		<if test='pagination.searchDateType == \"reqDate\" '> "
			+ " 			AND apprInfo.REQ_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "        			
			+ " 		<if test='pagination.searchDateType == \"apprDate\" '> "
			+ " 			AND apprInfo.APPR_DT BETWEEN TO_DATE(#{pagination.startDate} || '000000', 'YYYYMMDD HH24:mi:ss')"
			+ "					AND TO_DATE(#{pagination.endDate} || '235959', 'YYYYMMDD HH24:mi:ss') "
			+ "			</if> "
			+ " 		<if test='pagination.workType != \"\" '> "
	        + " 			AND apprInfo.WORK_TYPE in (${pagination.workType}) "
	        + "			</if> "        			
	        + " 		<if test='pagination.reqType != \"\" '> "
	        + " 			AND apprInfo.REQ_TYPE = #{pagination.reqType} "
	        + "			</if> "        			
	        + " 		<if test='pagination.status != \"\" '> "
	        + " 			AND apprInfo.STATUS IN ( ${pagination.status} ) "
	        + "			</if> "
	        + " 		<if test='pagination.keyword != \"\" '> "
	        + " 			AND apprInfo.keyword LIKE '%' || #{pagination.keyword} || '%' "
	        + "			</if> "        
			+ " 		<if test='pagination.reqEmpName != \"\" '> "
	        + " 			AND reqEmp.NAME LIKE '%' || #{pagination.reqEmpName} || '%' "
	        + "			</if> "  
	        + " <choose> "
	        + "		<when test='pagination.searchDateOrderType == \"reqDate\"' > "
	        + "			ORDER BY apprInfo.req_dt ${pagination.orderType} "
	        + "		</when> "
	        + "		<when test='pagination.searchDateOrderType == \"apprDate\"' > "
	        + "			ORDER BY apprInfo.appr_dt ${pagination.orderType} nulls last"
	        + "		</when> "
	        + "		<otherwise> "
	        + "			ORDER BY apprInfo.req_dt DESC "
	        + "		</otherwise> "
	        + " </choose> "
			+"</script>";
	@Select(READ_APPROVAL_ANSWER_LIST_FOR_EXCEL)
	public List<ApprovalForList> readApprovalAnswerListForExcel(@Param(value="pagination")ApprovalPagination pagination, @Param("availableApprWorkTypeList")List<String> availableApprWorkTypeList );
	
	public static final String READ_APPROVAL_NOTI_LIST_COUNT = "<script>"
			+ " SELECT count(apprInfo.SEQ) "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.APPR_EMP_ID = #{loginEmpId} "
			+ " 	AND apprInfo.status != 'ARST-0004' "
			+ " 	AND apprInfo.status = 'ARST-0001' "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='availableApprWorkTypeList.size != 0 '> "
			+ " 			AND apprInfo.work_type in "
			+ " 			<foreach item= \"workType\" index=\"index\" collection=\"availableApprWorkTypeList\" open=\"(\" separator=\",\" close=\")\" > "
			+ " 				#{workType} "
			+ " 			</foreach> "
			+ "			</if> "
			+"</script>";
	@Select(READ_APPROVAL_NOTI_LIST_COUNT)
	public int readApprovalNotiListCount(@Param("loginEmpId")String loginEmpId, @Param(value="availableApprWorkTypeList")List<String> availableApprWorkTypeList);

	
	public static final String READ_APPROVAL_NOTI_LIST = "<script>"
			+ " SELECT Z.* FROM ( "
			+ " SELECT ROWNUM as RNUM, X.* FROM ( "
			+ " SELECT "
			+ " 	 apprInfo.SEQ "
			+ " 	,apprInfo.CONTENT_SEQ as contentSeq "
			+ "		,apprInfo.WORK_TYPE as workType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.WORK_TYPE) workTypeName "
			+ "		,apprInfo.REQ_TYPE as reqType "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.REQ_TYPE) reqTypeName "
			+ "		,apprInfo.STATUS "
			+ "		,(SELECT NAME FROM KPC_ADMIN_CODE WHERE CODE=apprInfo.STATUS) statusName "
			+ "		,apprInfo.REF_ID as refId "
			+ "		,apprInfo.REF_TITLE as refTitle "
			+ "		,apprInfo.DESCRIPTION "
			+ "		,apprInfo.KEYWORD "
			+ "		,apprInfo.REQ_EMP_ID as reqEmpId "
			+ "		,reqEmp.name as reqEmpName "
			+ "		,apprInfo.REQ_DT AS reqDate "
			+ "		,apprInfo.REQ_MEMO as reqMemo "
			+ "		,apprInfo.APPR_EMP_ID as apprEmpId "
			+ "		,apprEmp.name as apprEmpName "
			+ "		,apprInfo.APPR_DT AS apprDate "
			+ "		,apprInfo.APPR_MEMO as apprMemo "
			+ "		,apprInfo.CREATE_DT as createDate "
			+ "		,apprInfo.UPDATE_DT as updateDate "
			+ " FROM "
			+ "		KPC_APPROVAL apprInfo, KPC_EMPLOYE reqEmp, KPC_EMPLOYE apprEmp "
			+ " WHERE "
			+ " 	apprInfo.APPR_EMP_ID = #{pagination.loginEmpId} "
			+ " 	AND apprInfo.status != 'ARST-0004' "
			+ " 	AND apprInfo.status = 'ARST-0001' "
			+ " 	AND apprInfo.req_emp_id = reqEmp.emp_id "
			+ " 	AND apprInfo.appr_emp_id = apprEmp.emp_id "
			+ " 		<if test='availableApprWorkTypeList.size != 0 '> "
			+ " 			AND apprInfo.work_type in "
			+ " 			<foreach item= \"workType\" index=\"index\" collection=\"availableApprWorkTypeList\" open=\"(\" separator=\",\" close=\")\" > "
			+ " 				#{workType} "
			+ " 			</foreach> "
			+ "			</if> "
			+ "		ORDER BY apprInfo.req_dt DESC "
			+" ) X "
			+ " WHERE ROWNUM &lt;= (#{pagination.offset} + #{pagination.limit}) "
			+" ) Z "
			+ " WHERE RNUM &gt; #{pagination.offset} "
			+"</script>";
	@Select(READ_APPROVAL_NOTI_LIST)
	public List<ApprovalForList> readApprovalNotiList(@Param(value="pagination")ApprovalPagination pagination, @Param("availableApprWorkTypeList")List<String> availableApprWorkTypeList );
	
	public static final String EXIST_APPROVAL_REQUEST = " SELECT "
			+ "	case when count(tmp.merchant_id) > 0 then 1 else 0 end as result "
			+ "	FROM "
			+ "		MERCHANT_TMP tmp,"
			+ "		KPC_EL_APPR appr "
			+ "	WHERE "
			+ "	tmp.seq = appr.tmp_seq "
			+ "	AND tmp.merchant_id = #{merchantId}"
			+ "	AND appr.status IN ( 'ARST-0001', 'ARST-0005' ) ";
	@Select(EXIST_APPROVAL_REQUEST)
	public boolean existApprovalRequest(@Param("merchantId")String merchantId);
	
}
